from app.models import db, Bug


def seed_bugs():

    bug_fixes_1 = Bug(type="Basic", title="Bug Fixing", description="Fix any type of bugs in your Websites", delivery_time=1, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=3, price=10)
    bug_fixes_2 = Bug(type="Basic", title="Starter Package", description="Will fix any issue related to HTML / CSS / PHP / JS in your existing wordpress website.", delivery_time=2, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=0, price=50)
    bug_fixes_3 = Bug(type="Basic", title="Html, Css, and Js Fixing Pack1", description="Normal issues fixing", delivery_time=1, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=888, price=5)
    bug_fixes_4 = Bug(type="Basic", title="Silver", description="I'll fix one simple bug", delivery_time=3, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=1, price=20)
    bug_fixes_5 = Bug(type="Basic", title="bug fixes", description="I will get your WordPress or html website to working again after resolving issues and bugs", delivery_time=1, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=888, price=5)
    bug_fixes_6 = Bug(type="Basic", title="Fix bugs in an hour for $10", description="Fix your any html, css and responsive problems in an hour", delivery_time=1, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=888, price=10)
    bug_fixes_7 = Bug(type="Basic", title="Basic Plan", description="1-2 small issues", delivery_time=3, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=2, price=20)
    bug_fixes_8 = Bug(type="Basic", title="Silver: Fix only one single bug", description="One single PHP and WordPress bug fix in your website related to HTML, CSS, JS, jQuery, and PHP", delivery_time=1, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=1, price=25)
    bug_fixes_9 = Bug(type="Basic", title="Small fix", description="I will fix your html css for wordpress..", delivery_time=2, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=2, price=5)
    bug_fixes_10 = Bug(type="Basic", title="Basic", description="Fix Single Issue (15 min work)", delivery_time=1, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=0, price=5)
    bug_fixes_11 = Bug(type="Basic", title="Debugging", description="Fix bugs in your code or add a simple functionality", delivery_time=1, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=3, price=25)
    bug_fixes_12 = Bug(type="Basic", title="Fix small issue of website", description="I will fix small issue inside this and let you know the problem", delivery_time=2, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=3, price=5)
    bug_fixes_13 = Bug(type="Basic", title="web page Debugger", description="I will fix any of your HTML and CSS, JS issues or offer to Customize your page", delivery_time=2, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=888, price=5)
    bug_fixes_14 = Bug(type="Basic", title="Basic", description="I will fix one or two bugs for your css javascript vue and node js", delivery_time=1, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=3, price=10)
    bug_fixes_15 = Bug(type="Basic", title="Investigate a small, simple bug", description="I'll investigate the issue, track its cause in the code and propose a solution.", delivery_time=3, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=1, price=10)
    bug_fixes_16 = Bug(type="Basic", title="Single Bug Fix", description="Fix One Small Website and eCommerce Store issue.", delivery_time=1, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=0, price=5)
    bug_fixes_17 = Bug(type="Basic", title="I will investigate and fix", description="If your issue does not match with my description please contact with me first.", delivery_time=5, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=0, price=15)
    bug_fixes_18 = Bug(type="Basic", title="Basic", description="2 small html/css/responsive bugs", delivery_time=1, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=1, price=10)
    bug_fixes_19 = Bug(type="Basic", title="Basic", description="Fixing a Single Issue (Please order Gigs similar to number of issues)", delivery_time=2, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=1, price=10)
    bug_fixes_20 = Bug(type="Basic", title="Basic", description="i will fix a single issue from your Core PHP/Laravel/Codeigniter Websites", delivery_time=1, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=1, price=5)
    bug_fixes_21 = Bug(type="Basic", title="Laravel issues", description="fix and debug your website and web application that built with laravel ", delivery_time=1, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=0, price=20)
    bug_fixes_22 = Bug(type="Basic", title="fixing bug", description="fix ONE specific layout or code bug in your webpage", delivery_time=3, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=1, price=50)
    bug_fixes_23 = Bug(type="Basic", title="TWO CHANGE", description="I will work TWO issue of HTML,CSS", delivery_time=2, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=1, price=15)
    bug_fixes_24 = Bug(type="Basic", title="Website HTML & CSS Edit", description="Edit CSS and HTML of your website Fix Mobile view of your website Fix email setting", delivery_time=1, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=1, price=5)
    bug_fixes_25 = Bug(type="Basic", title="Basic Package", description="Fix all types bugs build in Laravel (Overall 2 hours Work). Please contact me before placing order.", delivery_time=3, bug_investigation=True, fix_documentation=False, detailed_code=False, revisions=0, price=35)

    db.session.add(bug_fixes_1)
    db.session.add(bug_fixes_2)
    db.session.add(bug_fixes_3)
    db.session.add(bug_fixes_4)
    db.session.add(bug_fixes_5)
    db.session.add(bug_fixes_6)
    db.session.add(bug_fixes_7)
    db.session.add(bug_fixes_8)
    db.session.add(bug_fixes_9)
    db.session.add(bug_fixes_10)
    db.session.add(bug_fixes_11)
    db.session.add(bug_fixes_12)
    db.session.add(bug_fixes_13)
    db.session.add(bug_fixes_14)
    db.session.add(bug_fixes_15)
    db.session.add(bug_fixes_16)
    db.session.add(bug_fixes_17)
    db.session.add(bug_fixes_18)
    db.session.add(bug_fixes_19)
    db.session.add(bug_fixes_20)
    db.session.add(bug_fixes_21)
    db.session.add(bug_fixes_22)
    db.session.add(bug_fixes_23)
    db.session.add(bug_fixes_24)
    db.session.add(bug_fixes_25)

    bug_fixes_26 = Bug(type="Standard", title="Html, Css, and Js Fixing Pack2", description="Medium complex issues fixing", delivery_time=2, bug_investigation=True, fix_documentation=False, detailed_code=True, revisions=888, price=20)
    bug_fixes_27 = Bug(type="Standard", title="Gold", description="I'll code small sized script.", delivery_time=5, bug_investigation=True, fix_documentation=False, detailed_code=True, revisions=3, price=40)
    bug_fixes_28 = Bug(type="Standard", title="Standard Plan", description="3-4 small issues", delivery_time=3, bug_investigation=True, fix_documentation=True, detailed_code=False, revisions=2, price=35)
    bug_fixes_29 = Bug(type="Standard", title="Gold: Fix three bugs", description="3 PHP and WordPress bug fix in your website related to HTML, CSS, JS, jQuery, and PHP", delivery_time=2, bug_investigation=True, fix_documentation=True, detailed_code=False, revisions=2, price=60)
    bug_fixes_30 = Bug(type="Standard", title="Medium Fixing", description="I will fix your html css for wordpress.", delivery_time=4, bug_investigation=True, fix_documentation=True, detailed_code=False, revisions=3, price=20)
    bug_fixes_31 = Bug(type="Standard", title="Debugging / Custom Code", description="Fix extensive bugs or code in javascript, HTML/CSS, JQuery for you.", delivery_time=5, bug_investigation=True, fix_documentation=False, detailed_code=True, revisions=5, price=60)
    bug_fixes_32 = Bug(type="Standard", title="Complex issue in website", description="I will fix complex problem under this package like contact form work, slider issue, navigation issue", delivery_time=3, bug_investigation=True, fix_documentation=False, detailed_code=True, revisions=888, price=15)
    bug_fixes_33 = Bug(type="Standard", title="Standard", description="I will fix two to three bugs or add new feature to your application", delivery_time=1, bug_investigation=True, fix_documentation=True, detailed_code=False, revisions=5, price=20)
    bug_fixes_34 = Bug(type="Standard", title="Investigate a couple of simple bugs", description="I'll investigate 2-3 issues, track their causes in the code and propose solutions.", delivery_time=4, bug_investigation=True, fix_documentation=True, detailed_code=False, revisions=1, price=20)
    bug_fixes_35 = Bug(type="Standard", title="Find and Fix", description="Find and Fix Major issue in Website and eCommerce Store", delivery_time=2, bug_investigation=True, fix_documentation=True, detailed_code=False, revisions=0, price=25)
    bug_fixes_36 = Bug(type="Standard", title="First Delivery", description="If your issue does not match with my description please contact with me first.", delivery_time=2, bug_investigation=True, fix_documentation=True, detailed_code=False, revisions=0, price=20)
    bug_fixes_37 = Bug(type="Standard", title="Standard", description="Page layout issues (html + css + responsive issues max. 5 bugs)", delivery_time=3, bug_investigation=True, fix_documentation=True, detailed_code=False, revisions=3, price=25)

    db.session.add(bug_fixes_26)
    db.session.add(bug_fixes_27)
    db.session.add(bug_fixes_28)
    db.session.add(bug_fixes_29)
    db.session.add(bug_fixes_30)
    db.session.add(bug_fixes_31)
    db.session.add(bug_fixes_32)
    db.session.add(bug_fixes_33)
    db.session.add(bug_fixes_34)
    db.session.add(bug_fixes_35)
    db.session.add(bug_fixes_36)
    db.session.add(bug_fixes_37)

    bug_fixes_38 = Bug(type="Premium", title="Html, Css, and Js Fixing Pack3", description="Html, Css, and Js Fixing Pack3", delivery_time=3, bug_investigation=True, fix_documentation=True, detailed_code=True, revisions=888, price=50)
    bug_fixes_39 = Bug(type="Premium", title="Platinum", description="Platinum", delivery_time=7, bug_investigation=True, fix_documentation=True, detailed_code=True, revisions=5, price=70)
    bug_fixes_40 = Bug(type="Premium", title="Premium Plan", description="Premium Plan", delivery_time=3, bug_investigation=True, fix_documentation=True, detailed_code=True, revisions=2, price=70)
    bug_fixes_41 = Bug(type="Premium", title="Platinum: Fix multiple bugs", description="Platinum: Fix multiple bugs", delivery_time=4, bug_investigation=True, fix_documentation=True, detailed_code=True, revisions=3, price=100)
    bug_fixes_42 = Bug(type="Premium", title="Complete Fixing", description="Complete Fixing", delivery_time=7, bug_investigation=True, fix_documentation=True, detailed_code=True, revisions=4, price=100)
    bug_fixes_43 = Bug(type="Premium", title="Debugging / Complete Custom Website", description="Debugging / Complete Custom Website", delivery_time=7, bug_investigation=True, fix_documentation=True, detailed_code=True, revisions=7, price=150)
    bug_fixes_44 = Bug(type="Premium", title="Complex issue fix with source code", description="Complex issue fix with source code", delivery_time=3, bug_investigation=True, fix_documentation=True, detailed_code=True, revisions=888, price=25)
    bug_fixes_45 = Bug(type="Premium", title="Premium", description="Premium", delivery_time=5, bug_investigation=True, fix_documentation=True, detailed_code=True, revisions=7, price=100)
    bug_fixes_46 = Bug(type="Premium", title="Investigate a more complex issue", description="Investigate a more complex issue", delivery_time=5, bug_investigation=True, fix_documentation=True, detailed_code=True, revisions=1, price=50)
    bug_fixes_47 = Bug(type="Premium", title="Full Support", description="Full Support", delivery_time=5, bug_investigation=True, fix_documentation=True, detailed_code=True, revisions=0, price=45)
    bug_fixes_48 = Bug(type="Premium", title="Extra First Delivery", description="Extra First Delivery", delivery_time=1, bug_investigation=True, fix_documentation=True, detailed_code=True, revisions=0, price=30)
    bug_fixes_49 = Bug(type="Premium", title="Premium", description="Premium", delivery_time=5, bug_investigation=True, fix_documentation=True, detailed_code=True, revisions=888, price=60)

    db.session.add(bug_fixes_38)
    db.session.add(bug_fixes_39)
    db.session.add(bug_fixes_40)
    db.session.add(bug_fixes_41)
    db.session.add(bug_fixes_42)
    db.session.add(bug_fixes_43)
    db.session.add(bug_fixes_44)
    db.session.add(bug_fixes_45)
    db.session.add(bug_fixes_46)
    db.session.add(bug_fixes_47)
    db.session.add(bug_fixes_48)
    db.session.add(bug_fixes_49)

    db.session.commit()


# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and resets
# the auto incrementing primary key
def undo_bugs():
    db.session.execute('TRUNCATE Bugs RESTART IDENTITY CASCADE;')
    db.session.commit()
