from app.models import db, Service


def seed_services():
    service_1 = Service(publish=True, title="I will do web apps with PHP and mysql professionally", description="***ALWAYS DISCUSS FIRST BEFORE MAKING ORDER*** ***ALWAYS DISCUSS FIRST BEFORE MAKING ORDER*** ***ALWAYS DISCUSS FIRST BEFORE MAKING ORDER*** Hello Fiver I am Anas From Pakistan a nation of web developers! I am here to do all works regarding web developments,php,mysql,web apps and whatever you want. I have experience of doing big projects so just contact me i will never disappoint you and full fill your requirements professionally. I CAN DO : 1.Php Scripts. 2.Php With Mysql. 3.Web apps. 4.Web desiging. 5.Fix your php Scripts. and lots of more just contact me.",
                        listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/105267010/original/f1522fe650f34fda57b7bfd47106cce385d24af6/do-web-apps-with-php-and-mysql-professionally.jpg", user_id=3, category_id=1, service_language_id=6, web_package_id=1)
    service_2 = Service(publish=True, title="I will build web app for you", description="I will develop an awesome responsive web app from scratch for you. If you have a legacy website / web application or an exciting idea and you want a modern, responsive, scalable web application that can be easily accessible from anywhere, whether from phone or desktop, then this gig is perfect for you! Gig components : Responsive web app Any modern browser compatibility Clean maintainable code Live preview before delivery Skills: Vue.js, React.js, Nuxt, Laravel, Node.js, Express, MongoDB, MySQL, Firebase, PWA (Progressive Web Apps), SSR, SPA (Single Page Application) Kindly message me before placing an order, I respond quickly!",
                        listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/105267010/original/f1522fe650f34fda57b7bfd47106cce385d24af6/do-web-apps-with-php-and-mysql-professionally.jpg", user_id=4, category_id=1, service_language_id=4, web_package_id=2)
    service_3 = Service(publish=True, title="I will create web gis application using cesium, arcgis, mapbox", description="I offer a professional service to develop a 2D or 3D WebGIS or WebMap application for your custom requirements. My service includes a complete system infrastructure that includes data integration and pre-processing, geodata analytics, geodata visualization, and application deployment. About me: I'm Joe, a Geospatial Scientist with more than ten years of experience in the GIS field. My daily work includes developing and researching GIS Analyst and Automated Workflow in various projects for many clients. I am an expert in several GIS Tools, frameworks, and APIs including CesiumJS, ArcGIS, QGIS, FME, Deckgl, Here MAP, OSM, PostGIS, Google Map, Mapbox, etc. Example WEB GIS: >> Web Application for Construction Planner >> Web GeoPortal with GeoProcessing Tool >> 3D Building Model Web Viewer (glTF, 3D Tiles, i3s) >> 3D Real Estate WebMap >> 3D Route Tracking/ Routing API integration Free consultation: Feel free to message me your requirement, and we can discuss the process and work through your project together. ",
                        listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/183875998/original/1e5c468307cb253baed38dd5bbdb90b24f23a161/create-a-3d-web-application-with-cesiumjs.jpg", user_id=5, category_id=1, service_language_id=4, web_package_id=3)
    service_4 = Service(publish=True, title="I will develop and design fully responsive web applications", description="Hello,I can design and develop simple landing pages to full fledge web applications. My expertise are in front-end and back-end development using modern technologies like: Angular React Material Ui Bootstrap Redux Flex I can develop web applications with the features like: Responsive design Progressive Scalable Social media integration Payment method integration and many more. Please feel free to ping me at any time.",
                        listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/140492917/original/488321ca7de2e53c778ed4a89ceb77a414a05195/develop-and-design-fully-responsive-web-applications.png", user_id=6, category_id=1, service_language_id=4, web_package_id=4)
    service_5 = Service(publish=True, title="I will create bep20 token on binance smart chain", description="I will create and deploy your own Bep-20 Token On Binance Smart Chain with all standard functions of smart contract. Token Features: Transferable Tradable Mintable Burnable Secure Verified Contracts You can list and Trade it on any exchange What will you get : Bep-20 Token Development on Binance Smart Chain Deploy in Binance Smart Chain Verify Your Token on Binance Smart Chain **GAS FEE NOT INCLUDED** PLEASE FEEL FREE TO MESSAGE ME BEFORE PLACING AN ORDER. ",
                        listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/198800590/original/5f0e78d5e7ccedae9b3a70baea7d7001303f21b9/create-bep20-token-on-binance-smart-chain.png", user_id=7, category_id=1, service_language_id=1, web_package_id=5)
    service_6 = Service(publish=True, title="I will help you with twilio solutions in your project", description="I'm a Twilio Champion Contact me before ordering I can help you with Twilio, setting an API system for your SMS, Voip or Voice solution, integrate it with Zoho or any other CRM you have. Here a list of the most common integration I can build: Twilio SMS Twilio Bulk SMS Twilio Voice Call Twilio Call Forwarding Twilio Lookup API Twilio IVR Studio Twilio Call Recording Twilio SMS Forwarding  Twilio Voicemail ( with email forwarding Twilio SMS Autoresponder Twilio integration with Google Sheets Twilio / CRM integration Twilio Flex Twilio Pay Twilio IoT Twilio Whatsapp Twilio Authy And much more  I can also work with any other kind of API integration you need. I already built many integrations also with Intercom, aWeber, Zoho, Zapier, Facebook, Twitter, Podio, Google API, etc. Other than Twilio I can also help and work with you implementing MessageBird solutions. Let me know what exactly you need and I will be glad to help you. ",
                        listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/57188349/original/c25b35a54e3895e50ebc87a2425fb9a8ffe3782a/help-you-with-twilio-api.jpg", user_id=8, category_id=1, service_language_id=1, web_package_id=6)
    service_7 = Service(publish=True, title="I will write custom PHP script, php code", description="I am a Full Stack Web Developer having years of experience in Web Development. I have a great grip on PHP and can solve every problem related to Core PHP. If you have any problem related to your PHP script then you are at the right place.I will do:Refactoring your existing codeForm Validations on the server-sidewrite a custom PHP scriptbug fixingOr anything related to PHP codeI will do your work until you are satisfied.Note: Please message me before placing your order to estimate the Project amount and send you a custom offer.Thank You.",
                        listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/143775684/original/98e6bc5852ef07ebb61797808479d4f328697050/write-custom-php-script-php-code.png", user_id=9, category_id=1, service_language_id=6, web_package_id=7)
    service_8 = Service(publish=True, title="I will code anything in ruby on rails", description="Please Contact me before placing the order. Looking for a top notch Ruby on Rails Engineer? Yes You are on right place. Why me? Level 2 Seller Ruby on Rails Expert 4 years of Professional Experience Reliable Fastest Delivery What Services I Provide? Rails Installation / Configurations ( Remotely ) Rails Tuition Classes Any Bugs / Errors / Code Reviews Gems Installation Any Ruby Script Web Development in Rails Web Services Web Designing (HTML, CSS, BOOTSTRAP, JQUERY & JAVASCRIPT) Web Servers ( Puma, Webrick, Nginx and UniCorn ) Deployment ( Heroku, Digital Ocean, Amazon S3 ) If you have any questions and need any help, You can ask me about anything anytime, I also give free assistance to rails students. thanks bilal5110 ",
                        listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/18130029/original/0dc18ae753687c1e7dfb35f5059488919205650d/code-for-you-in-ruby-on-rails.jpg", user_id=10, category_id=1, service_language_id=3, web_package_id=8)
    service_9 = Service(publish=True, title="I will create website, debug, fix PHP scripts for you", description="Please ask for my availability before placing an order. This gig is solely for PHP Scripting. Aside from PHP scripting I also offer other services(w/c I will post as a new gigs soon) which can be writing from scratch, debugging, and testing the codes.I have full knowledge with the ff. programming tools and concept: Javascript  JQuery  CSS  HTML 5  PHP Frameworks (Laravel, CodeIgniter). Custom PHP Framework or coding from scratch Repositories (Github and Subversion). IMPORTANT NOTE: After order completion there will only be 4 days of free support for the related task/project. IF any bug, modification or additions it will be subject to a new gig already so please test it within the time period. Any orders/ question message me and let's have a nice talk. All inquiries are welcome. Thanks! ",
                        listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/5226061/original/raw2/write-debug-fix-php-scripts-for-you.JPG", user_id=11, category_id=1, service_language_id=3, web_package_id=9)
    service_10 = Service(publish=True, title="I will build online academy like udemy,kajabi,thinkific,teachable", description="Online School / Academy Worldwide Selling Web Consulting Service WHAT do I OFFER? More than 150 languages translator on real-time Premium look 100% Responsive Interactive layout Up to market standards 100% as per your requirements Valued experience developing Online Academy applications Pre & Post sale support and design alteration  Quality & professional work  Unit testing  Modules Included? Teacher Students Courses Admin  1 - Teacher Module Tacher Sign Up Teacher Login  Teachers Capabilities Teachers Dashboard Teachers Capabilities 2 - Students Module Students Sign Up Students Login  Students Enrollments Students Dashboard 3 - Courses Module Courses publishing Courses Name, Description, Why to take, Targeted audiences & many more Quizzes  Final Tests Checkout / Purchasing via supported methods like Pay-Pal / CC or any other required 4 - Admin Module Teachers Manager User-friendly Admin Dashboard TO manage on your own as well Courses Manager Students Manager Complete Access To Each Corner Of Website SIMILAR PROJECTS DONE :  https://academy.efixed.co/ https://www.cubeacademy.io/ http://eclipps.co/ https://brainowconsulting.com https://academy.lashesnskinbydaphne.com/ ", listing_img="https://fiverr-res.cloudinary.com/videos/so_1.121148,t_main1,q_auto,f_auto/akvdjnilvc9erqr8f50g/develop-online-academy-or-school-like-udemy-or-lynda-for-you.png", user_id=12, category_id=1, service_language_id=1, web_package_id=10)
    service_11 = Service(publish=True, title="I will automate a business process using zapier", description="Zapier is a tool which allows hundreds of different web apps to communicate and collaborate with each other. It can be used to speed up and automate your business workflows and processes in an infinite number of cool ways. You tell me what part of your business you want automated and I'll do it with Zapier. The apps Zapier support out the box are listed in the App Directory on Zapier. These can be tied together in pretty much any combination, using the various triggers/actions listed on the app page. Even if the app you want to automate is not listed, or the required trigger/action doesn't exist, there is still a possibility I can work some magic for you using webhooks and/or custom code steps. If you don't know what's possible, book the consultation step, tell me your idea and I'll research what's possible. ",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/101029300/original/46e3d308d94e03fda8458cff3e04f41c4661c700/automate-a-something-for-you-by-connecting-2-apps-on-zapier.png", user_id=13, category_id=1, service_language_id=1, web_package_id=11)
    service_12 = Service(publish=True, title="I will create top level erc20 token on ethereum blockchain", description="UPDATE: Due to the increasing gas fees on Ethereum, I can no longer afford to include the smart contract creation fee in my gig price.For 100$ (plus extras if you are interested) I will create the coolest thing in tech nowadays: your very own TOP-LEVEL customised ERC20 Token.   What exactly can you do with an ERC20 Token?  You can do many great things, and just to name a few: you can trade it on Exchanges (I can help you with that - see my Gig Extra), you can start your own ICO/IEO crowdsale and sell tokens to anyone interested or you can simply use it for developing your own projects. How awesome is that?  What I need from you: Token Name (ex. CARDANO) Symbol (ex. ADA) decimals: (18 is standard, 0 means your token is not divisible)  Free Bonus: If you purchase my gig, I will send you the source code in a separate file and I will verify the token’s contract source on etherscan.io, both free of price. So how come the price is only 100$?  I think 100$ is a fair price for this gig. But if you think it’s worth more, feel free to send me a tip, I won’t mind at all. If you have any questions, please contact me. ",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/107236646/original/73020f650d72fe1b187a6335510645900d3e0999/create-your-erc20-token-on-ethereum-blockchain.png", user_id=14, category_id=1, service_language_id=1, web_package_id=12)
    service_13 = Service(publish=True, title="I will do PHP,MySQL,Javascript development or bug fixes", description="I am an experienced PHP/MySQL developer. This gig covers one of: tracking down and fixing 1-2 bugs in your PHP/Javascript code debugging 1-2 performance problems in your MySQL database adding a PHP/Javascript feature or script making a change to your MySQL database (adding a new table for example) Generally speaking, these items will take one (possibly two) hours to complete. Please contact me for adding features and database design. ",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/6334721/original/working/do-php-mysql-javascript-development-or-bug-fixes.PNG", user_id=15, category_id=1, service_language_id=6, web_package_id=13)
    service_14 = Service(publish=True, title="I will develop custom php web application, website", description="Hello,This Gig is all about the best Quality PHP products. If you are looking for custom responsive website or web application then you are at right place. I will develop custom web application and website for you.  I am a professional full stack web application developer with professional experience of almost 5 years. I have developed many web application and website in recent years. I'm promised to give 100% satisfaction to my clients.  My skills: PHP, Laravel, HTML, CSS, Bootstrap, javaScript, jQuery, mySql, API You'll get: Modern, responsive, secured, quality system with good coding structure. Feel free to contact me to know more about my works. ",
                         listing_img="https://fiverr-res.cloudinary.com/videos/so_0.971855,t_main1,q_auto,f_auto/uy3omkufgckw3cdok2lm/develop-website-and-php-web-application.png", user_id=16, category_id=1, service_language_id=6, web_package_id=14)
    service_15 = Service(publish=True, title="I will do javascript html css jquery task", description="Are you stuck trying to add a new feature or design element on your website? Or just want someone to handle the entire job for you while you relax, here's what I'm offering! ➤ Work on Javascript to add new features or fix JS Bugs. ➤ Fix performance issues. ➤ Write HTML5 / CSS3 codes and fix any bugs. ➤ Do any JQuery task or just use Vanilla Javascript (As required). ➤ Do tasks related to web designing or some functions. ➤ Make website responsive or fix responsiveness issues. ➤ Add new CSS elements and designs. ➤ Third-Party API Integration. I can write scripts for specialized platforms likes: ➤ ClickFunnels ➤ WordPress CMS, WordPress themes ➤ kvCore website customization What to expect when hiring me? ✔ Robust and effective communication ✔ Results better than expectations ✔ Work delivered ON TIME! ✔ Flexible work timings that suit my clients I Would love to discuss your project with you in more detail. Send me a message now to get started. ",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/148484167/original/003156699152e1dc6ca7c8156d68ad53efad878e/do-javascript-html5-css3-jquery-bootstrap-task.png", user_id=17, category_id=1, service_language_id=4, web_package_id=15)
    service_16 = Service(publish=True, title="I will install any PHP script on your hosting or vps server", description="Ahoy,This is M. Hamza Iqbal from Pakistan, Through this GIG I will install PHP Script on your hosting or server. So you have bought a script from codecanyon or from any other platform and looking for somone who can install and modify that script, then you are at the right place, Order me here I am expert in doing this. Not only installation but also If you want any kind of modification then you can contact me as well. Please Note: Always contact me first before placing the order. If you want me to upgrade the preinstalled script then please first show me your current website and the script you want me to upgrade. ",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/138701201/original/b0871becb969fba7965eb1ba4731fc8563d3eba3/install-any-php-script-on-your-hosting-or-vps-server.jpg", user_id=18, category_id=1, service_language_id=6, web_package_id=16)
    service_17 = Service(publish=True, title="I will create any web calculator for wordpress and any website", description="I have an experience of 5+ years on web design and development. I have experience in building any sort of custom calculator for WordPress site. I can design and develop following online calculators for your website: I can do: Finance Calculators Roi Calculators Mortgage Calculators Excel to web conversion Fitness Calculators iframe based calculators Health Calculators Custom Calculators Clone online calculator WordPress calculator Send result to the user via E-mail Graph Calculators The print result or export result as CSV, PDF and Excel Sheet etc Database Integration Clone online calculator Bug fixing in the calculators Please inbox me before order. Compatible with: Web, Wordpress, SquareSpace, Drupal, Shopify, Magento and so on. My Special Offers Unlimited Revisions work until you fully satisfied Free small changes in future Your form/calculator will be: 100% responsive User friendly SEO friendly Bug free If you have any question, don't hesitate to ask me. Best Regards Abdullah ",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/182329724/original/022435cfe1738e3243e5e0110168ce24d30bb60d/create-any-calculator-for-your-wordpress-and-any-website.jpg", user_id=19, category_id=1, service_language_id=3, web_package_id=17)
    service_18 = Service(publish=True, title="I will help you with a javascript, html, and css project", description="Please contact me before purchasing an order so we can discuss your project and how to make it happen. In your message, try to include: 1. The problem(s)/frustration(s) that you'd like to resolve. 2. The value that would be gained from resolving them. 3. What you'd like me to do to help you resolve them NOTE: I AM A TECHNICAL EXPERT, NOT A DESIGNER. I can receive a design and turn it into code, but I am not as proficient when it comes to creating an aesthetic designs from scratch. In other words, I can easily make pretty things functional, but I am not as good at making a functional thing pretty. Have an idea for a web project or a want to add a new feature to what you have already? How about a script you just need to work a little differently. Got some HTML/CSS/JavaScript that is giving you a headache? I will help you with almost any HTML/CSS/JavaScript project. I have helped people with: Custom tools and full-stack web apps; redesigning their code to be simple, easy to follow, future-proof, and safe; modifying PHP code; scripts to fix bugs; tutoring; debugging; and other tweaks to take their websites to the next level of functionality. ",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/112807779/original/3c524085bcac24936885295b24cdc0c2814250da/create-a-small-to-medium-javascript-web-app-for-you.png", user_id=20, category_id=1, service_language_id=3, web_package_id=18)
    service_19 = Service(publish=True, title="I will add google map with dynamic markers and search", description="I am a professional software developer. I have 7 years of experience as a software developer. I have worked in ASP.Net web forms, ASP.Net windows forms, ASP.Net MVC, WCF, jQuery, Ajax, Android and Cordova/PhoneGap. Contact me if you need professional programming. In this Gig I will add google map to your web page. It can be a static page or dynamic (with PHP or ASP.Net). It will have the following functionalities. Get markers data from database with jQuery ajax and display on the map. Add search box and display location in the map. Add or remove markers from the map and save the data back to database using ajax. I can do any Google Maps API relevant work, like: Displaying KML files. Creating/generating KML files. Using the GeoXML3 library. Using the drawing library (drawing polygon, polyline, circle or rectangle). Adding autocomplete (a location search box). Using places library. Using the directions API. Adding clusters. Adding google map to PHP, .Net (MVC or Web Forms) or Android app (native or cordova/phonegap) applications. Please see below YouTube channel for some of the work we have done. https://www.youtube.com/channel/UCkSqn5WOF6Rof0BD_PnPHlw ",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/36113710/original/b62ef9a0eb4ab97aebb099e891af37f6745cb212/add-google-map-with-dynamic-markers-and-search.png", user_id=21, category_id=1, service_language_id=2, web_package_id=19)
    service_20 = Service(publish=True, title="I will supply a complete content management system", description="- Content Management System - SSL certificate (For site Security and Form Submissions) - Hosting on World-Class AWS - On-Page editor for quick changes to text - Form Management Area (Download all Form Data Instantly) - GDPR Compliant Form Server",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/165716320/original/e7dfbd0fa285c1607b79cccf02d7bbe9a29c97b4/supply-a-complete-content-management-system.jpg", user_id=22, category_id=1, service_language_id=1, web_package_id=20)
    service_21 = Service(publish=True, title="I will develop website using php, yii, yii2, codeigniter, laravel", description="Hello,Greetings of the day.  I am a full stack PHP developer, and have 10+ years of experience in web development, web app development.  are you looking to create a website, web application, fix any issue, bugs to on your website? then you are at Right GIG. Services: PHP  Yii  Yii2  CodeIgniter (CI) Laravel  SQL / Database SAAS CRUD API development / Third party API Integration (Google, Facebook ) Payment Gateway Integration (  PayPal, Stripe, and many more.. ) Codecanyon Scripts Integration JavaScript, Jquery, Ajax Website Speed Optimization Bug fix Social Media Login LMS  Food Delivery Applications   PHP Developer, Yii Developer, Yii2 Developer, CodeIgniter Developer (CI), Laravel Developer  also, I have expertise in Karenderia Multiple Restaurant System (KMRS online food ordering system), Kartero for food delivery. Karenderia Mobile app, Karenderia Driver app, Karenderia Merchant app, Karenderia user app Please discuss before ordering to make a job 100% success.  Thank you!",
                         listing_img="https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/114465392/original/9721e378413d4516630f7f58593fa55547458cb7/develop-website-web-app-using-php-laravel-codeigniter-yii.jpg", user_id=23, category_id=1, service_language_id=6, web_package_id=21)
    service_22 = Service(publish=True, title="I will create any calculator for your wordpress and non wordpress", description="I will create any online calculator for your wordpress and non-wordpress site (wix, squarespace etc) !!!Please contact me before placing the order. We will discuss all the details and you will get a calculator that fully meets your needs and at a fair price!!! !!!Please contact me BEFORE to order, for better execution of job.!!!  Please contact me for examples of previous works You'll get :   - Custom design of calculator - User friendly interface - Responsive design - Mobile optimization - Source code - My support - Images integration - Chart/graph  - Result of calculation to email  - Shortcode for wordpress - Wordpress plugin for your wordpress site - Options page - 100% free minor changes in the future I use: javascript, jquery, css, html, php !!!Please contact me BEFORE to order, for better execution of job.!!! ",
                         listing_img="https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/79756516/original/1260a98cfd3c620bd59af088d9822e54ba5b7452/create-any-calculator-for-wordpress.png", user_id=24, category_id=1, service_language_id=1, web_package_id=22)
    service_23 = Service(publish=True, title="I will develop website using PHP, codeigniter, laravel, wordpress", description="Available now for taking new orders! If you are looking for a Web Team who is dedicated and an expert in PHP, LARAVEL, CODEIGNITER, VueJs, WordPress then you are at Right Gig. we have extensive experience in web development, web app development and we can get you a professional website from scratch by using PHP, Laravel, Codeigniter, and WordPress. Also, if you are facing any issues on your website? leave it on us! we will fix your bugs and also show you what the problem was.! Services offered in this gig: PHP  Laravel  CodeIgniter (CI) SQL / MongoDB SAAS Develop a complete website from scratch Add New features Fixing bugs from your existing script Upgrading to the latest version Payment Gateway Integration ( PayPal, Stripe, and many more.. ) Website Speed Optimization Website On-page SEO Optimization Code Canyon Scripts Integration & Modifications Social Media Login ★•••★ I turn your ideas and dreams into working software ★•••★ Please discuss before ordering to make a job 100% successful.  ⚠️ Don't apply to hire us regardless of the quality of the results if you are looking for the cheapest developer(s). Thanks  Regards  Rashid Ashraf & Team",
                         listing_img="https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/109116477/original/ffbd2add5958318a547ff782f1523d59bf253469/fix-any-issue-or-create-php-codeigniter-website.png", user_id=25, category_id=1, service_language_id=6, web_package_id=23)
    service_24 = Service(publish=True, title="I will create interactive data visualizations with d3", description="Please contact me before ordering with your project description so I can assist you according to your specific needs. I stumbled upon data visualization while working as a physicist, and I've been passionately distilling insights from data and communicating findings with the superpower of visualizations ever since. I will be your invaluable resource for: You want to transform your data into Accurate, Straightforward and Aesthetically Pleasing visualizations (I call them my ASAP standard) on the web. Let me help you with that! If you have data, I can assist you to choose the right chart type to achieve your visualization goal. If you have a mockup, I can code up the visualization according to your mockup specification. If you have a chart already, I can help redesign and improve the chart with more appealing aesthetics and more engaging user interactions. If you have any other requests, no matter it is a static figure or an interactive webpage, I am happy to discuss your project details with you.  I am looking forward to working with reliable and trustworthy clients just like you. If you have any questions or requests, please click the 'Get a Quote' to contact me!",
                         listing_img="https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/105634882/original/a919c05027bdf6fa3a27de8f5c6b8427d012f36e/create-interactive-attractive-and-informative-d3-charts.png", user_id=26, category_id=1, service_language_id=1, web_package_id=24)
    service_25 = Service(publish=True, title="I will build a custom monday app ", description="It must be irritating, right? Getting bombarded by messages from people that tell you they know how to build your product properly, but they actually don't. Let me be candid with you: I've been there too. Most service providers focus on just technical stuff. Oh, you want an API? Yes, I can build the integration for you. Oh yes, and I can also create a video, and actually everything, just put an order on Fiverr! No! I want you to understand my business idea, so you can help me find the best solution to my users' problem! Sounds familiar? Now, let me cut through the noise and quickly introduce myself: My name's Vladimir, I help entrepreneurs like you build custom Monday Apps. I focus on helping YOU solve the problem of your users. I speak your language: You don't need to try and pretend you know everything about APIs, integrations, all these boring things. The technical part is on me. I just need your creative vision to implement the idea into life. Before my Gig gets PACKED with orders again, drop me a line about your project.",
                         listing_img="https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/206745906/original/7e5d9e63ad19628bcb56875d2067344862afb085/build-a-custom-monday-app-033b.png", user_id=27, category_id=1, service_language_id=1, web_package_id=25)
    service_26 = Service(publish=True, title="I will do custom web development ", description="Businesses that use complex software are often started by visionaries with experience in niche industries.  You’ve likely succeeded by creating products or services that resonate with your audience, rather than learning technical details or graphic design standards. At the same time, hiring and managing employees with skill sets beyond your own expertise can become a real nightmare. Save time and money by outsourcing design and technology implementation of your web applications. Developing solutions that bring results is real art.  That is why our team consists of dedicated experts only.  All of them are experienced professionals with a deep understanding and passion for their craft. Here are a few of the ways we can help you keep your website running smoothly: Backups and Recovery Security Patch Implementation Performance Optimization Bug Fixes Design Changes & Improvements New Website Pages Content Updates Tutorial Videos SEO Improvements Hosting Updates Platform-based Updates Consulting Calls Sounds like a good fit? Contact me today to discuss your site and start getting results.", listing_img="https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/126118509/original/64f91de4368b2bd07b40f86bb13d15aa3c518a3e/do-custom-web-development.png", user_id=28, category_id=1, service_language_id=3, web_package_id=26)
    service_27 = Service(publish=True, title="I will create online calculator or form for your wordpress or any website ", description="You need custom form integration or custom calculator on your site? I'll help you. Form or calculator can be integrated with database, pdf export or html Email for results export. I can provide solution for any requirement.  If you use WordPress - I can offer shortcode integration or custom WordPress plugin. Your form/calculator will be: ✔ 100% responsive ✔ User friendly ✔ Bug free ✔ SEO friendly Before the order we'll discuss: ✔ Mockup/design of your form ✔ Behavoiur an calculation rules ✔ PDF/EMAIL/CHARTS ✔ price and delivery time Price starts only from 50$ (form up to 5 fields, calculator up to 5 dependencies and formulas). Having 8+ years of experience in web-development (php/js/html5/css3), I'll suggest the fastest and clean solution.",
                         listing_img="https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/108156566/original/c074ec03ef525f41d8cd5b451e1f9aa8ecba749d/create-custom-js-calculator-or-form-on-your-site.jpg", user_id=29, category_id=1, service_language_id=1, web_package_id=27)
    service_28 = Service(publish=True, title="I will install, setup and customize erpnext for you ", description="I am an experienced Python and ERP developer having 6+ years of experience. I will customize erpnext to any level and to any extent from the latest version installation to print and form customization and to new module and app development. I can also provide training to use ERPNext ",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/139021752/original/0234be722829b4f4a60b66b55b3cd9192db32480/install-setup-and-customize-erpnext-for-you.jpg", user_id=30, category_id=1, service_language_id=7, web_package_id=28)

    db.session.add(service_1)
    db.session.add(service_2)
    db.session.add(service_3)
    db.session.add(service_4)
    db.session.add(service_5)
    db.session.add(service_6)
    db.session.add(service_7)
    db.session.add(service_8)
    db.session.add(service_9)
    db.session.add(service_10)
    db.session.add(service_11)
    db.session.add(service_12)
    db.session.add(service_13)
    db.session.add(service_14)
    db.session.add(service_15)
    db.session.add(service_16)
    db.session.add(service_17)
    db.session.add(service_18)
    db.session.add(service_19)
    db.session.add(service_20)
    db.session.add(service_21)
    db.session.add(service_22)
    db.session.add(service_23)
    db.session.add(service_24)
    db.session.add(service_25)
    db.session.add(service_26)
    db.session.add(service_27)
    db.session.add(service_28)

    service_29 = Service(publish=True, title="I will develop custom business website and web application", description="I will use advanced and Modern technologies to build your application.I have 8 Years of experience. You will also able to Manage Users in your system.you will have all basic and advanced functionalities in your system. I provide services like: POS System, Pharmacy Management System, Stock Management System, Cafe inventory system, Store Management system, Sales Management System, Hospital management system, Accounting management system, Traveling management system, Air Ticketing System, Multivendor Application, Ecommerce Website, Payment Api Integration, Business websites, >>> Please Discuss your Project with me Before Ordering <<",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/181660535/original/e113282f83daf72f478da62df9a18423dcf40caa/design-and-develop-professional-website-using-php.png", user_id=31, category_id=2, service_language_id=3, web_package_id=29)
    service_30 = Service(publish=True, title="I will do html5, css3, bootstrap, javascript, jquery, php, scripts", description="Are you looking for a Javascript developer to work on your projects? I will write code in Javascript, JQuery, Typescript, PHP, HTML, CSS, Bootstrap and SQL for custom websites. Here is the list of services I do and fix:  ✓ JavaScript & JQuery issues or bugs.   ✓ Vanilla JS and AJAX. ✓ PHP and JavaScript custom scripts. ✓ HTML, CSS and JavaScript coding in ClickFunnels. ✓ Bootstrap Responsive. ✓ HTML5 & CSS3. ✓ JQuery Validation. ✓ Cross platform compatibility and new feature development. ✓ Adding new features in Angular website. ✓ Bug fixation and adding new features in Angular website. ✓ SQL issues and queries. ✓ Optimized and documented code. ✓ Generic bugs fixation. Please discuss the requirements before placing an order. Thank you.",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/158709244/original/83c38c74ebfbc2cbe8634c0ca3cc6c63713165c2/do-html5-css3-bootstrap-javascript-jquery-php.png", user_id=32, category_id=2, service_language_id=3, web_package_id=30)
    service_31 = Service(publish=True, title="I will do web design html,css,bs4,js and backend with php,mysql", description="Hi I am professional web developer working form some years I develop many websites for different customers and fix bugs. Please feel free to contact me for any kind of website weather it is small or with huge database. Also contact me for HTML CSS issue. My expertise are in PHP, Wordpress, SQL, HTML, HTML5, CSS, CSS3, jQuery, Javascript, Google AMP. I use highly recommenced tools to write or run code, Notepad++, Wamp Server, Please also contact me for any CSS, HTML projects., NOTE: Message me first before placing the order.",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/124968726/original/2effe49ecf6d83eef5b6b8d4371cf4bbb4c66574/can-fix-your-bugs-in-no-time-related-to-web-programming.jpg", user_id=33, category_id=2, service_language_id=16, web_package_id=31)
    service_32 = Service(publish=True, title="I will edit Html Css to make your page more attractive and fix related bugs", description="****Please Knock me before Order******* Hi, I am CodemasterJamil. I will help you to make your webpage more attractive by editing Html Css and fixing related issues. I will do fro you: **Add or Remove page Contents. **Fix positioning and spacing related issues. **Place logo images or any kind of element in right place. **Change colors, create shadows and effects to make it more attractive. **Make it cross browser compatible . **Find and solve html css related errors. **W3C validation.",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/25275652/original/a840b6e8ee1f42ee5d6ccab5521f86810c5b1f48/fix-html-css-bugs-errors-and-edit-your-site.jpg", user_id=34, category_id=2, service_language_id=3, web_package_id=32)
    service_33 = Service(publish=True, title="I will develop responsive web for you", description="I'm a web developer with almost 4 years of experience in web design and development using entity framework/mvc fameworks.I used agile methodologies for web development.I will develop full stack website using: HTML, CSS, Bootstrap, JSON, PHP, .NET, WIX, Wordpress, Scratch, AJAX, JS, MVC Framework, Entity Framework. I will develop site like: Land pages, Management systems, Shopify, Protofolia, Product related site, Content Management System, School Management System, Social Media Site, Chatting sites, Online Quiz, Management System, Custom Websites according to your requirements",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/25275652/original/a840b6e8ee1f42ee5d6ccab5521f86810c5b1f48/fix-html-css-bugs-errors-and-edit-your-site.jpg", user_id=35, category_id=2, service_language_id=6, web_package_id=33)
    service_34 = Service(publish=True, title="I will design and develop a professional website for you", description="If you are looking for someone who can develop and design a professional website for your business or organization, then you are in the right place. I will do web development for you in a short time with HTML5, CSS, Javascript, latest animations and transitions and all the features like Signup and Login feasibility, database integration. One of the key features that a site need is a Modern Design combined with a great User Interface. Being a web designer & a developer I can provide you with a high-end website that will turn your site visitors into clients.  I will do professional website development for you using HTML5, CSS3, Javascript, Jquery PHP, and AJAX, WordPress. You Will Get : Responsive designs to all screens Custom Eye_catching designs Modern animations and transitions efficient and functional back-end creative user interface real-time functionality will be available at your time Quality guaranteed Professional look Professional website I design and develop a professional website along with a detailed timeline plan keeping in mind every single aspect of customer needs and demand, and give my level best to meet customer needs at any cost.",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/136433179/original/2adb44ff3f7df57e995e55a73f56a506d3ec9c39/design-and-develop-a-professional-website-for-you.jpg", user_id=36, category_id=2, service_language_id=4, web_package_id=34)
    service_35 = Service(publish=True, title="I will install, upgrade, migrate and customize moodle", description="A web designer/developer with 8+ years of experience in moodle Learning Management System is here to help you. I can do any moodle work and make your Learning Management System up and running smoothly. My service includes Planning, Installing, Optimizing and Configuring Moodle Moodle Upgradation (including major version upgrades from 1.x to 2.x or 3.x). Moodle Customization. Theme Design. Server Migration.  Backup and Restoration. SSL Certificate Installation Wordpress and Joomla Integration. Woocommerce Integration. Linux Server Configuration for Moodle. Windows Server Configuration for Moodle. Administration and Troubleshooting. Edwiser Bridge Configuration. Big Blue Button Installation and Configuration. The basic gig ($15) offers only a fresh moodle installation or a minor version upgrade.   I also provide error fixing and troubleshooting service. Please use the 'Get a Quote' form to send the details of the error. If you have more complex requirements use the 'Get a Quote' form. I am more than happy to help and I do respond within a few hours. Quick response,  World-Class Customer Service and 100% satisfaction guaranteed. ", listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/8578827/original/d7f902643404ea714b3c12fe627f0d49bd6d6a39/do-moodle-installation-or-upgradation.jpg", user_id=37, category_id=2, service_language_id=1, web_package_id=35)
    service_36 = Service(publish=True, title="I will upload your html css files to your ftp server", description="*NO DESCENT WORK, ONLY BEST SERVICE HERE! Quality & Guarantee. +800 project done and happy customers* IMPORTANT!!! PLEASE PLEASE DON'T ORDER MY GIG UNTIL WE AGREE! CONTACT ME FIRST! Thanks for considering my gig. You obviously are looking for a quality service and you have come to the right place. Have ready web files and a server? Don't have time? Don't know how to install it? Ok, I can resolve your problems with just $5 (10 webpages) More than 10 html webpages or want to install WordPress and database? Want me to build/design a website from scratch using html/css/javascript/php/bootstrap/Wordpress? Check my gig extra or contact me directly to have a quote! The gig will be delivered at the latest 2 days. If you are urgent, i offer the fast delivery option Important - Don't order my gig until we agree. My objective is not money, If you don't review my work, i will not work with you again. Each design has its price. Don't order the gig and disappear. For more questions, requirements and specifications please send me a message. All my prices are negotiable! Thanks and i look forward to working with you!",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/2597760/original/1af61896fa7fade48b11536fed8a08bf98b2f7c1/upload-your-html-files-to-your-ftp-server.jpg", user_id=38, category_id=2, service_language_id=3, web_package_id=36)
    service_37 = Service(publish=True, title="I will do shopify custom coding or bug fixing and customization", description="Hello Buyers! Are you looking for someone to do any custom coding or bug fixing and shopify store modification? Then you are on right place. i will fix your problem quickly and effectively within time.i have designed more than 300 shopify stores. I Will Create or Modify Your Store as Per Your Requirements. NOTE: 'THE PROJECT WILL BE BACKED WITH 100% MONEY BACK GUARANTEE'.  NOTE: 'PLEASE SEND ME YOUR REQUIREMENTS BEFORE PLACING ORDER'. MY SERVICES ARE: ->Fixing Shopify bugs ->HTML/CSS/JAVASCRIPT related issues in shopify ->Custom Theme Development ->Shopify Liquid Coding ->Shopify Customization ->Shopify Plugin Integration ->Shopify Theme Design ->Product Addition ->Custom Coding For Shopify store ->All Pages Modifications and creation ->And Much More. WHY TO CHOOSE ME: ->worked over 300 Shopify stores ->Quick Response ->Start Working instantly ->Order Deliver Within Time.  'PLEASE NOTE GIG PRICE IS NOT FIXED IT WILL INCREASE OR DECREASE AS PER YOUR REQUIREMENTS'.",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/152796061/original/ea197cc20ecd9bda93b1f57e5f6eba5b68b2cb02/fix-any-bug-or-theme-customization-of-your-shopify-store.jpg", user_id=39, category_id=2, service_language_id=1, web_package_id=37)
    service_38 = Service(publish=True, title="I will do anything for u in kajabi", description="I can do anything for you in kajabi like e;g customize your website,create landing page or sales page  make website for you in kajabi etc..",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs2/110227462/original/2ad31f6a932784041a57e293be7d547e672f8cee/do-anything-for-u-in-kajabi.png", user_id=40, category_id=2, service_language_id=1, web_package_id=38)
    service_39 = Service(publish=True, title="I will develop design and fix php websites or web applications", description="I'm a PHP/JAVASCRIPT specialist I will be glad to help you. I can help you with any kind of PHP or design styling issues. This may include server side error, fetching of data or any other kind of programming issue.LEAVE IT TO ME i will resolve it. I can create a whole website for you from scratch. I will assist you in creating a new website, catching and fixing the bugs. I have more than 5 years experience in simple and frameworks of PHP. I have done many projects. I am providing following service. Debug and fix PHP code. Create new website from scratch. Installation of script. Fix any HTML / HTML5,Bootstrap or  CSS / CSS3 styling issue. Fix any javascript/Jquery issue. Write PHP code as per your requirement. API Integrations. Or any other work related to PHP websites. Please contact me first before making any order and explain in detail what you want me to do.",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/125076243/original/f4085aae33c6029b2564d0608e4f071bf6a2ce48/develop-and-design-php-websites-and-web-applications.jpg", user_id=41, category_id=2, service_language_id=4, web_package_id=39)
    service_40 = Service(publish=True, title="I will develop react js web app by node js,express,mongo", description="Hi There,Thank you for reviewing my gig! I am an experienced React (JavaScript) Developer expert in developing user-friendly Web Apps. If you want professionally developed react js web application in a very reasonable budget then you are at the right place. With 5+ years of experience in web development, I can develop any kind of web app that fits according to your needs and business requirements. Expertise in: React JS Redux React Material UI Bootstrap 4 Rest API Integration Node Js Mongo DB Build Restful apisBenefits you'll have:1. Fully documented source code.2. Project delivery within the deadline.Regards,ZulqurnainNOTE:If you are not sure which package suits your needs. Just send me a quick message and we can quickly have a discussion about your needs and I’ll share which option could be best for you.",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/148629759/original/ddb0ffafc2ccbf2f9c78f8407851c4c68ff0b962/develop-react-web-app-using-reactjs-redux-and-material-ui.png", user_id=42, category_id=2, service_language_id=4, web_package_id=40)
    service_41 = Service(publish=True, title="I will fix or develop any php,codeigniter,laravel,wordpress website", description="Premium & Professional Developer for your Web or App Projects with : Laravel , Wordpress, Codeigniter, Bootstrap, HTML issue, CSS issue, JavaScript issue jQuery issue API Development Payment Gateways I don't only do modifications or fixes, I can develop your entire website or app! Only Quality Work / Unlimited Revisions & Fast Turnaround! Contact Me Before Place An Order",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/146421804/original/b78806f9494cbab6173395eca5bb497fac6d1382/fix-or-develop-any-php-codeigniter-laravel-wordpress-website.jpg", user_id=43, category_id=2, service_language_id=16, web_package_id=41)
    service_42 = Service(publish=True, title="I will develop, fix or install any PHP laravel website", description="Are you facing any problem with your Laravel web application or want to add a new feature to your PHP Laravel web application? Then you're in the right place. I am an experienced full-stack web developer and can get you a professional website from scratch using Laravel. I can also build you a complete site using only PHP. I will add new features to your web application, or install your codecanyon scripts to your server.  What I offer : ❆ Install any PHP Laravel script to your server. ❆ Add new features to your existing website. ❆ Payment gateway integration (PayPal, Stripe, Mollie, and many more) ❆ Updgrade your PHP Laravel website ❆ Social media Login  ❆ Customized Admin panel ❆ Integrate external API to your site ❆ SEO and user-friendly concept ❆ E-commerce development  ❆ Develop any website from scratch using Laravel or core PHP. I am specialized in :  ✓ HTML  ✓ CSS  ✓ PHP ✓ Laravel ✓ JQuery ✓ JavaScriptNote: Please message me with your requirements before placing an order.",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/166256532/original/5df19e6a3ab4772b9dd880254f9601ad4914710d/php-laravel-laraveldeveloper-phplaravel-php-website.png", user_id=44, category_id=2, service_language_id=6, web_package_id=42)
    service_43 = Service(publish=True, title="I will do react, laravel, python, symfony, nodejs, angular web", description="I will do anything related to JavaScript/NodeJS/laravel/python such as web app, mobile app, fix bugs... I normally work with: ReactJS, React Native NativeScript  Laravel NodeJS Python Angular 2+, AngularJS jQuery Bootstrap framework Google Materialize WordPress JavaScript jQuery UI Google Map API Google APIs Slides, drop and drag apps, navigation menus HTML widgets Validate forms HTML5 Canvas PSD to HTML Charts. Explain me what you need and how long you need it, I will give you a custom offer or tell you what extras to book. Please contact me before place the order.",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/101522007/original/4bfaca78f2ea2f2ecc71d337235f9d919e9fe96d/make-responsive-website-mobile-application.png", user_id=45, category_id=2, service_language_id=16, web_package_id=43)
    service_44 = Service(publish=True, title="I will do custom css, html, javascript, PHP coding", description="Hello,Want a custom website built for your business? Or Having trouble in recognizing or fixing the issues/bugs in your existing website/blog. It is not a problem because I'm here to fix any issues in HTML, CSS, Bootstrap jquery, javascript, PHP or database(Mysql/Oracle). Things I offer: CRM development E-commerce Development Custom website development (both front-end and back-end) with Laravel, PHP and MySQL Vue.js, HTML, CSS, Boostrap, Javascript/Jquery, PHP single/multi web page, Complete website creation from scratch using Laravel Rest Api and vue.js Web Application with proper exception handling Can work with APIs, integrate API's in your applications. Responsive - Mobile Friendly sites. Great UI/UX for your site. PSD to HTML, XD to HTML or any other design to HTML with best quality and pixel perfect design Fix issues in front-end or add some changes to it. Bug Investigation and Bug fixing. MySQL database design and integration in websites. MySQL database bugs fixing and integration issues fixing. I will do the work until you are satisfied with fast and responsive communication.", listing_img="https://fiverr-res.cloudinary.com/videos/so_28.791422,t_main1,q_auto,f_auto/bcbb1yyatbpkzmghxaty/html-css-javascript-codes-and-online-forms.png", user_id=46, category_id=2, service_language_id=16, web_package_id=44)
    service_45 = Service(publish=True, title="I will do html css, web programming, editing, PSD to html", description="Hi,I am professional web developer working form 7 years I develop many websites for different companies. I use agile methodology to develop best product. I do clean coding which is easy to customize. Please feel free to contact me for any kind of website whether it's with small or with huge database. Also contact me for HTML CSS issue or PSD TO HTML. My expertise are in PHP Codeignator Wordpress SQL HTML HTML5 PSD TO HTML CSS CSS3 jQuery Javascript SEO ADOBE  I am also providing some free services to my clients. FREE BACKUP FREE UPLOAD I use highly recommenced tools to write or run code Notepad++ Wamp Server Live Server Adobe Dreamweaver File Zilla  Please also contact me for any CSS, HTML projects. NOTE: Message me first before placing the order. ",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/79670756/original/0b171697a812cd934794e5635eb2535c789a1f57/do-web-programming-editing-also-fix-css-html-of-website.jpg", user_id=47, category_id=2, service_language_id=6, web_package_id=45)
    service_46 = Service(publish=True, title="I will be your front end developer, will do front end development", description="Over the last 9 years i have been working as a front end developer, having strong command on any design format conversion into Html,(psd to html, xd to html, sketch to html, zeplin to html etc), Html5, Css3, Bootstrap, jQuery, Less, Sass, Scss, Zurb foundation, Materialize, Responsive Web templates, Mobile templates, Mobile apps front end development and all front end related technologies. Feel Free to share your designs in any format from below: 1) Psd 2) Abode Xd 3) Adobe Illustrator 4) Zeplin 5) Sketch 6) PNG 6) JPG  I worked for so many clients with Positive feedback's and have good relations with them. Feel free to share your projects it will be an honor to work with you... Before start the order ! Please Text ME to discuss the project details ... thank you in advance ) Best. ",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/106567773/original/16cbe753b021b7aa26ead8b250f6e25a74127b09/do-front-end-development.jpg", user_id=48, category_id=2, service_language_id=3, web_package_id=46)
    service_47 = Service(publish=True, title="I will integrate google map api into your website", description="i will Integrate google map on your website. Features  Road map website map HYBRID map Apply markers on locations Info window on marker Routs b/w two address Note  Please Contact me before Order  Thanks in Advance ",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/117929113/original/b5bc3c70ee8d46e1b8dfe952ef351092e3fb39c0/integrate-google-map-api-into-your-website.png", user_id=49, category_id=2, service_language_id=1, web_package_id=47)
    service_48 = Service(publish=True, title="I will be your front end developer and designer", description="Before start the order ! Please Text ME to discuss the project details. I am professional Senior Front End developer as a PSD2HTML specialist since 2013, In my professional career i have done more then 350 projects with different techniques, i have strong grip on Bootstrap, Sass, Less, Zurb-Foundation, Jquery and css3. If you want to convert your PSD, XD, AI, Zeplin, Sketch, PNG or JPG  file into responsive website you are at right place and we can discuss the work and proceed. Following are some of my core skills. HTML5. CSS3. Bootstrap. Zurb Foundation. Materialize. SASS. LESS. JQuery. Responsive template. Cross-browser compatibility. Pixel perfect design. Clean code. Integrate custom fonts. W3C validated",
                         listing_img="https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/107251673/original/9d5b49ce1280bb40a3285745f9f164327100990a/be-your-front-end-developer-and-designer.png", user_id=50, category_id=2, service_language_id=3, web_package_id=48)
    service_49 = Service(publish=True, title="I will build your company website in 24 hours", description="Looking for a professional business website delivered fast?. You landed on the right page!. I will build for you a quality WordPress website based on your business niche, delivered within 24 hours (*express delivery). The website will be modern, intuitive and easy-to-be-managed through the Admin Panel. You will be able to upload your own images and text with just a few clicks. Every package ensures that your website will be: SEO structured, Responsive on any device, Fast, Secure. For the development process, a WordPress Premium Template will be used. I will customize the fonts and colors to match your brand. Ready to start? Place an order. Have a question? Drop me a message. To ensure a smooth working process, please read the FAQ section below. This gig is exclusively intended for businesses and individuals who are expecting quick deliveries.",
                         listing_img="https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/189953932/original/84c9b02178c94cf1fe74d8f217ba3a93ab2287a2/build-your-business-website.png", user_id=51, category_id=2, service_language_id=1, web_package_id=49)
    service_50 = Service(publish=True, title="I will design and develop cos pages in hubspot",
                         description="Dear Buyer, Thank you for visiting my Best Selling Hubspot Gig. I'm a Certified Hubspot Developer, in my career of 6+ years, I have not just developed Hubspot Websites but also build a lot of custom functionalities that are challenging in nature. It includes Custom Calculators, Quiz, Booking modules, etc. Moreover, I have a strong base in the usage of Animation plugins like GSAP inside Hubspot as well. My Expertise: - PSD to HubSpot. - Hubspot to WordPress - Hubspot Custom site Design and Development  - Hubspot Blog, Landing page, and Email template design and development - Website Migration  - Static HTML website to Dynamic(Hubspot). - Custom Template design and development. - Mobile responsive. - Parallax website. - Hubdb. - Custom calculator. Gig Features: # Modular based design [easily swap block] # 100% Editable Clean HTML Source Code. # Table based design # Inline CSS # 100% satisfaction guaranteed # Fast response ---- Please contact me before placing the order---- If you have other requirements like any kind of IT services related to Design and Development contact me first. Thanks and Regards, Ruchir K. ", listing_img="https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/18898717/original/13dc42a85e9e6a8d09a679a2e67af6996868ddc8/any-hubspot-work-for-you.jpg", user_id=52, category_id=2, service_language_id=3, web_package_id=50)
    service_51 = Service(publish=True, title="I will develop, fix custom PHP website for you", description="Hi, Do you want to fix issues on your website? Do you want to develop a custom PHP website?  Then you have come to the right place. I am a full stack developer having two years of experience in designing and developing web applications using PHP, MySQL, HTML, CSS, JS. I am providing the following services on this gig: My Basic Package Services: PHP, MySQL related tasks. HTML, CSS, JS related tasks, Bootstrap related tasks, Bugs fixing, Detailed code comments, Code documentation, Consultation/help in your projects. My Standard Package Services: Maximum 5 pages PHP CRUD web application Admin Panel to manage your web application Ensure website security by ensuring security measures such as using Prepared Statements for SQL queries. 6 months free post-management support. Well organized code & logic. My Premium Package Services: More than 5 pages PHP CRUD web application. Admin Panel to manage your web application. Ensure website security by ensuring security measures such as using Prepared Statements for SQL queries. 6 months free post-management support. Well organized code & logic. Note: Order me! I bet you won't regret it. Feel free to contact me. Kind Regards, Hassan Javaid",
                         listing_img="https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/145418188/original/7bf54205a7fa887e3be0fc15615ef459e2beee62/do-php-mysql-html-css-javascript-bootstrap-related-tasks.png", user_id=53, category_id=2, service_language_id=6, web_package_id=51)
    service_52 = Service(publish=True, title="I will create a professional website for your business", description="With over 19 years of experience in various creative industries and roles, I have acquired a wealth of knowledge and skills. My work is clean, dynamic, and always buyer-focused. I value client relationships and work to deliver the most effective and highest quality services. I want to make sure we’ll be a terrific fit so let’s connect for on a 5-minute chat to discuss your job. Are you looking for a professional landing page with high potential for conversions? I will design and develop such a page in WordPress or HTML. Make your business succeed and increase your sales! What's the process? • Send all the required details • Within 5 to 8 days, I will send you the initial design to appraise • You evaluate the design and determine any changes that you want implemented • I make the necessary revisions and resubmit them for final approval • Once the design is approved I’ll develop the code of the landing page! Depending of your budget and functionalities I can do custom design or use a theme template in order to save some money and time. Please keep in mind that this option would not be available for complex sites.",
                         listing_img="https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/134434914/original/2819d17a10c2e2f78b18fa9924577107a6d0961d/create-a-professional-website-for-your-business.jpg", user_id=54, category_id=2, service_language_id=1, web_package_id=52)
    service_53 = Service(publish=True, title="I will do frontend web development in HTML CSS javascript", description="Hi there! Are you looking for a Frontend Developer to build a responsive, stunning, and the user-friendly website from scratch or looking someone to redesign & develop your existing website, then you are in the right place! What you can think I can develop it for you! I am Ismail, A Professional Frontend  Developer providing reliable web services for a custom website since 2017. Gig Includes: Edit HTML page or CSS. PSD TO HTML. Edit/Modify/Fix CSS, Edit/Modify/Fix html forms. Add/Edit forms (HTML/CSS). Edit/Modify navigation & menus. Edit modify color schemes of the website. HTML to REACT. I will use GitHub to deploy for testing it online and also can deploy on your computer with free hosting. (Limited Time Offer). You will gain the following advantages from me: Clean code, Pixel perfect design, Custom, fonts and icons, Responsive design for PC, Mobile, Tablet ★Why me? Your satisfaction is my guarantee, therefore I’ll work until you are 100% satisfied Premium quality and timely results. Communication throughout the whole process ✉ *********** PLEASE ASK BEFORE ORDERING *********** ✉ Thanks. Regards, Muhammad Ismail", listing_img="https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/162059015/original/bb73209cbc4be71fd0d6f3a09f69cc4fdb1e2850/be-your-front-end-web-developer.png", user_id=55, category_id=2, service_language_id=1, web_package_id=53)
    service_54 = Service(publish=True, title="I will build website in vuejs,reactjs,nodejs, firebase and website design", description=" <<<OUR CLIENTS SATISFACTION IS ULTIMATE GOAL>>> Greetings, We are team of Software Experts who provide services in Website Development and Mobile Development for Past 4 years and have hundreds of clients from all over the World. We help you from step to end in the Software life cycle and client’s satisfaction is our ultimate goal. Requirements=>Design=>Development=>Testing>Deployment. So feel free drop us a message to discuss your product. Our Services: website design and build website, UI development, Desktop Application, APIs integration, Complete Front-end Backend for your site, Firebase Integration, Ecommerce shopify solutions, Hybrid Mobile developmentJava, , cpp, c projects Programming, Python programming, bugs fixing, development. Technologies we work in: Web Platforms: Front-end, Vuejs, ReactJs, Angular, Back-end, Nodejs Firebase, Mysql, PHP, Ecommerce platform, Shopify, Mobile Platforms, Native Apps, Android App Development, IOS Development, Hybrid Apps, React Native, Ionic, Flutter, Why to choose us?? Experienced Staff, Reasonable prices, Get comments in the code explaining it. Free Test Cases. Unlimited revision.## Please contact us before placing the order.",
                         listing_img="https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/149265014/original/3e98cf235d6987aa50404387bbcaef85f5efdbc4/java-c-project-python-web-design-hmtl-css-desktop-javascript.jpeg", user_id=56, category_id=2, service_language_id=4, web_package_id=54)
    service_55 = Service(publish=True, title="I will develop php web admin dashboard, portal or panel", description="Hello & Welcome to my gig! Hopefully you are fine! I am highly skilled and passionate seller with 4 years+ experience. I can design and develop fully responsive and cross browser compatible web apps, cms, admin dashboad, portal, panels and management systems professionally in quick delivery time and at low cost.  Why choose me? Highly skilled and passionate seller. Provide 100% professional and quality work. Money Back guarantee Unlimited Revisions  Support and Maintenance. My Tools and Technologies: PHP , HTML5 & CSS3 , Boostrap, VueJs, NodeJs, JavaScript, JQuery, Ajax , MySQL. Gig Services: Full Responsive Website or CMS Creation, Web Admin Dashboard, Panel or Portal, API Creation and, Integration, Script Writing and Integration, Add New Functionality, Website Customization and Modification, Fix Bugs / Errors / Issues, And Much More++ Please contact before placing the order provide me all details in PDF or word document. I'll be looking forward for long term working relations with you. If you have any query, feel free to discuss. Regards, Altoorsoln",
                         listing_img="https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/114474133/original/35387cbaddcf257670b08ac1cb3e410a32821eeb/develop-web-admin-dashboard-portal-or-panel.jpg", user_id=57, category_id=2, service_language_id=6, web_package_id=55)

    db.session.add(service_29)
    db.session.add(service_30)
    db.session.add(service_31)
    db.session.add(service_32)
    db.session.add(service_33)
    db.session.add(service_34)
    db.session.add(service_35)
    db.session.add(service_36)
    db.session.add(service_37)
    db.session.add(service_38)
    db.session.add(service_39)
    db.session.add(service_40)
    db.session.add(service_41)
    db.session.add(service_42)
    db.session.add(service_43)
    db.session.add(service_44)
    db.session.add(service_45)
    db.session.add(service_46)
    db.session.add(service_47)
    db.session.add(service_48)
    db.session.add(service_49)
    db.session.add(service_50)
    db.session.add(service_51)
    db.session.add(service_52)
    db.session.add(service_53)
    db.session.add(service_54)
    db.session.add(service_55)

    service_56=Service(publish=True,title="I will fix your wordpress, php, html, jquery, css, database errors",description="Greetings,I am Full stack web developer having 5+ years of experience. I can handle everything what you thrown up me. I will fix any bugs, issues or errors on your website. I will Fix PHP Errors or bugs for sure I will Fix Responsive Design issues or bugs I will Fix Javascript errors / bugs I will Fix jQuery issues or Errors I will Codeigniter errors or bugs I will fix Laravel Errors I will fix or solve issues or errors in wordpress Just  tell me clearly the bug you see. I'm always online, so I can answer your messages as soon as Possible. I'm also open for any kind of other requirements on Responsive Web design, Web Development and Mobile App Development. Guaranteed Solution.!!! Thanks and Regards, iTechOza ",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/111698587/original/6956f45681d1787b8525f34baad43106f35e4f32/fix-any-html-css-jquery-javascript-php-bugs-error-issues.jpg",user_id=58,category_id=3,service_language_id=16,web_package_id=1)
    service_57=Service(publish=True,title="I will fix styling or coding wordpress issues",description="Will fix minor wordpress issues which includes following: Website Responsiveness issue HTML / CSS / PHP / SEO based issue Custom plugin issue coding issue Note:  * Please, contact using personal message (PM) before placing any order so i can estimate the time of delivery and cost. * Gig won't be considered without pre-order discussion and approval because sometimes it takes more time to resolve even a minor issue. * Order Priority will be based on Higher cost basis. ",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/20345307/original/afec539c24cf3ae2e7228a314a8629367dbdeeb5/fix-styling-or-coding-wordpress-issues.png",user_id=59,category_id=3,service_language_id=3,web_package_id=2)
    service_58=Service(publish=True,title="I will fix or debug any html, css, js and wordpress issues",description=" Welcome To Html, Css, and Js Debugging/Fixing Gig! Have you been looking to fixing or debugging html, css, js and wordpress? Well search no further because in this very professional html, css, js and wordpress gig I'll do and fix your all of the issues. Such as layout issues, responsive issues or any other issues that you have been bothering. And also I will help you with your web design and programming needs using HTML, CSS, JS and WordPress. Even I'll help you to  build something from scratch or do some modifications. I can also fix your wordpress issues or do some changes.  Why you should choose me? Quality work. Reliable service. Low cost. Support After order completion. Services: 1. Website fixing/bugs debugging/removing. 2. Website responsive issues. 3. Website changes/modifications. 4. Website transferring/moving(One hosting to another) Contact with your requirements to get the quote for the job. Please don't order the $5 gig for the full website or major additions/modifications if you have no idea how much it should cost.  Thank you. ",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/99835332/original/e18131e941fd85999a3db94285468a321522dda3/convert-psd-to-html.jpg",user_id=60,category_id=3,service_language_id=3,web_package_id=3)
    service_59=Service(publish=True,title="I will code or fix javascript, jquery",description="PLEASE CONTACT ME BEFORE PLACING AN ORDER. If you want to buy the basic package, please provide me with a single script file that contains a single bug. The script must contain less than 50 lines of code. Providing a website or multiple files is not accepted in this package. In all other cases, please contact me first, I'll let you know which package is suitable for your request. If your requirements are beyond the scope of any package, I'll provide you with a custom quote. Offerings: JavaScript, jQuery, Ajax Bug Fix JavaScript, jQuery Customization New Feature Implementation Node, React, HTML, CSS, Bootstrap Bug Fix and Customization ",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/133026193/original/ca564ef8191d910df52bd6ac1c5d6898cd7bde2e/code-javascript-fix-javascript.png",user_id=61,category_id=3,service_language_id=4,web_package_id=4)
    service_60=Service(publish=True,title="I will fix html, css, wordpress issues and bugs",description="Note: ✉ *********** PLEASE ASK BEFORE ORDERING *********** ✉'DO NOT PLACE ORDER DIRECTLY BEFORE DISCUSSION' I can help you with : ✓ Fixing any WordPress errors ✓ Performing theme customizations ✓ Fixing CSS issues in your html website ✓ Customizing HTML and CSS This is not the exhaustive list of what I can do. Please discuss with me your custom requirements and I will try my best to assist you. Thanks ",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/135174256/original/e60d13ab987221e83f782d0e0ba3a340485dd3f1/fix-html-css-wordpress-issues-and-bugs.jpg",user_id=62,category_id=3,service_language_id=3,web_package_id=5)
    service_61=Service(publish=True,title="I will fix html css bootstrap issues in an hour",description="PLEASE CONTACT ME FIRST WITH DETAILS BEFORE PLACING AN ORDER. Hi, Bugs on your website? Can't handle it yourself? Looking for a fix? Need HTML/CSS bugs fixed? I will fix any kind of HTML CSS & Bootstrap issue of your site within an hour. Bug fixing is not a rocket science! It's a baby playing piano for me! I will also consult you to improve your site's speed and layout. This gig helps you to Fix any kind of HTML error Fix any CSS bugs Solve any responsive issue Fix bootstrap bugs Improve page load and layout Browser compatibility issue Fix typography issue Fix Cross-browser problem (guarantee) Why choose me? Huge experience in each particular area 100% Satisfaction Guarantee 300+ 5 star review Unlimited revisions and free support Deliver project within the deadline Best quality at an affordable price Deliver in an hour (Most of the time) Kind Regards Golak ",listing_img="https://fiverr-res.cloudinary.com/videos/so_0.663301,t_main1,q_auto,f_auto/uuvdnovuy8gboa6tqcck/fix-html-css-bootstrap-issues-in-an-hour.png",user_id=63,category_id=3,service_language_id=3,web_package_id=6)
    service_62=Service(publish=True,title="I will rapidly fix html, css, wordpress and responsive issues",description="I'm glad to see you here. Please contact me before placing an order so I can assist you better. :) I'm providing my services on Fiverr since 2015 and till now I'm having the highest success score and great client satisfaction. I can assist you to add/fix/edit HTML CSS Bootstrap Responsive design WordPress Expertise in the following things Design related issues Mobile Responsiveness Fonts & Color combination Adding new features using HTML, CSS, Jquery Fixing WordPress issues  Why choose me? 100% Satisfaction Guarantee 100% Money-Back guarantee if not satisfied Quality at best price So let's start working :) ",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/39618610/original/3e7224878c5fc397face4934781b3780d9a7aba7/do-little-css-changes-in-your-website.jpg",user_id=64,category_id=3,service_language_id=3,web_package_id=7)
    service_63=Service(publish=True,title="I will do PHP and wordpress bug fix just within 2 hours",description="Got stuck with WordPress Issue? Facing difficulty in programming? Unable to catch the bugs? Fixing WordPress problems and errors can be troublesome and intimidating for some people. Please leave it to me as I am a PHP and WordPress developer with over 5+ years of experience! I will do PHP and WordPress bug fix just within 2 hours with Html, CSS, PHP bugs and show you what the problem was. Bug fixing Services by me Any design, style, and CSS changes Debug and fix PHP code. WordPress configurations issue Fix Layout Issues  Fix any Small HTML5 and JavaScript changes Forms fixes and modifications Fix any JavaScript & jQuery issue. Fix any Foundation & Bootstrap issue. Fix Responsive Issues PHP and WordPress bug fix And much more... Just let me know your problem, and I will fix them instantly. Do you need immediate service? Everything related to PHP and WordPress bug fix can be done here! Most orders handled within 12 to 24 hours unless the task needs more time! Fast & Quick service is available it will be an absolute pleasure to help you. Please send me a message before order to check immediate availability. Please note this is one issue per gig.  ",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/171092078/original/f4f91e1bcf77bb639be18321312f46567b7216f0/do-php-and-wordpress-bug-fix-just-within-2-hours.jpg",user_id=65,category_id=3,service_language_id=1,web_package_id=8)
    service_64=Service(publish=True,title="I will fix css html php wordpress",description="Are you looking for a wordpress, Html, Css pro? I can help you in: ✓ fixing wordpress errors ✓ theme customizations ✓ fixing wordpress theme css issues ✓ plugin errors ✓ custom themes ✓ Fixing Html or CSS issues ✓ Installation and setup and so on.. Please note that it's 1 gig per small task. If you have more than 1 task or a bigger project, You can always contact me in my inbox to discuss it and get a best custom deal. Thanks ",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/25338117/original/a8349ddc8216295db0138240bf46023519286a8c/fix-css-html-php-wordpress.jpg",user_id=66,category_id=3,service_language_id=3,web_package_id=9)
    service_65=Service(publish=True,title="I will fix any html, css, javascript errors, website bugs or issues",description="CONTACT ME BEFORE PLACE ANY ORDER Here's the list of what I offer: Fix any HTML, CSS, javascript errors and bugs Fix WordPress Errors / Layout Problems W3C Validation (HTML / CSS) for SEO Convert Icons to Web Fonts ( @font-face ) Work related to JavaScript / jQuery (e.g Sliders, Tabs, Gallery, LightBox, etc) Speed Up your Website to Load Faster (Google PageSpeed Insights, Tools Pingdom) Making Responsive Layouts/Elements/Navigation/ Mega Menus) ",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/90562701/original/2efb936eb6ad65c1257e56f9ff1c16ab104bbf8d/fix-any-html-css-javascript-errors-website-bugs-or-issues.png",user_id=67,category_id=3,service_language_id=4,web_package_id=10)
    service_66=Service(publish=True,title="I will write javascript, html, css, php, jquery code for you",description="Hey!if you are having problems with your website/blog and can't seem to figure out what the problem is then you have landed on the right gig. I will thoroughly inspect your code to figure out the issue and fix it. I have experience in working with various technologies and can fix any issues related to: Javascript HTML CSS JQuery PHP Python Java JSP Database (MySQL, SQLserver, Oracle) ASP.Net Even if you don't see the relevant technology listed above, you can still contact me and I will most likely be able to help you out. Things you can get done: Fix bugs Fix front-end (changing colors, alignment, font, complete revamp) Web pages with HTML/CSS/Javascript Java/JSP pages Making website responsive / mobile friendly UI / UX design API Integration, fetching data from API and displaying it on web page Create complete custom website I will complete your work with utmost satisfaction and will keep you updated with everything. I can also explain the technical aspect of your work if you're interested. Fee free to contact me any time and make sure that you do contact me before placing the order, I'll quickly respond to you and we will get started with your work. ",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/146314477/original/f8da38dc1843be3058e4f304222bb1d9124e9dd7/code-javascript-for-you.jpg",user_id=68,category_id=3,service_language_id=1,web_package_id=11)
    service_67=Service(publish=True,title="I will fix your html, css, jquery, wordpress issues",description="★★★ High rated 3000+ successfully completed orders ( 100% positive ratings ) ★★★ Are you facing any layout issue or difficulty in programming, Don't worry leave it to me, i will fix html, css, jquery, php, javascript, bootstrap, wordpress, shopify issue. i will also show you where was the issue. I will fix one html,css, jquery issue for $5 We also Provide : - Install Wordpress and Shopify themes. - Domain and Hosting Services. - Website Migration, SSL installation - PSD to highly optimized responsive html ( Gig link https://bit.ly/2JuP2lR ) - PSD to Wordpress theme ( Gig link https://bit.ly/2MgqTgt ) - Any Jquery or Wordpress plugin integration. - Wordpress website development and customization Please check my wordpress website development and customization gig https://bit.ly/2MgqTgt Your questions will be answered in 2 -3 hours on normal working days Most of time it more quicker, we love you and know how to treat. Note: If you have any doubts and questions please message me for your queries and custom quote. ",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/3763945/original/Untitled-1/fix-your-html-css-issues--2.jpg",user_id=69,category_id=3,service_language_id=1,web_package_id=12)
    service_68=Service(publish=True,title="I will edit or fix any html, css, javascript code in 48 hrs max",description="do you have a problem with your HTML and css code and doesn't know how fix it or you want change or add something to your HTML page then your in the right place with this service you will get: fix Any Html / Html5 Bugs fix Any CSS / CSS3 Bugs fix Any Javascript / JQuery Bugs Add any changes to your existing web page fix website responsive issue Css style customization less than 48 hours delivery clean high quality code Why Hire Me? 100% satisfaction unlimited revisions Professional Service at Lowest Cost Full Support and Consultancy. Faster Turn Around  100% money back guarantee  Note: please contact me before order to help making your order delivery even faster. Also for custom requests feel free to contact me to discuss it further. ",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/117869593/original/93ad78c22db1ef352971c75b7fe13174895bef53/help-you-edit-or-fix-any-html-and-css-issues.jpg",user_id=70,category_id=3,service_language_id=3,web_package_id=13)
    service_69=Service(publish=True,title="I will fix html css javascript vue js and node js bugs",description="NOTE: PLEASE INBOX US BEFORE PLACING AN ORDER. Hi there, We are a team of Full-stack VUE and NODE(express) JS developers. We have more than one year of experience in VUE and NODE JS stack. This gig offers solutions for any kind of CSS , JAVASCRIPT VUE, and NODE(express) JS bugs you face while developing a web application. GIG FEATURES : ☑️ will fix bugs for your CSS, javascript, vue, and node js. ☑️ will solve issues related to the responsiveness of websites. ☑️ will fix issues related to javascript for example AJAX, API integration. ☑️ will fix issues related to VUE js for example Vue router, Vuex, API integration any other issue. ☑️ will fix issues related to Node js for the express framework. ☑️ will fix issues related to databases like MongoDB and MYSQL. ☑️ FREE LOGO FOR YOUR WEBSITE. WHY US : ☑️ BUG FIX at an affordable amount. ☑️ Effective Communication. ☑️ Experience in Web Development. ☑️ Well documented and clean code. ☑️ Server upload (if needed).  ☑️ Great customer support. Looking forward to working for you.  Regards, Team Code Lab. ",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/173043058/original/409be65dcfe91cc2a531af9b6288392fc6f5547a/fix-html-css-javascript-vue-js-and-node-js-bugs.jpg",user_id=71,category_id=3,service_language_id=4,web_package_id=14)
    service_70=Service(publish=True,title="I will debug your c sharp dot net, java or php program",description="I'll help you solve any problem you might have in a program's source code: I'll work with you on discovering the issue and tracking down the root cause. Additionally, instructions and advice will be provided on how to remedy the problem. On request, I can also provide a custom offer for fixes or other changes. Supported programming languages: C# for console, Windows Forms or WPF. Java for console, for desktop and for Android. PHP Javascript Swift Objective-C Perl - only basic scripts Python - only basic scripts Please contact me before placing an order, there are frameworks or tech stacks that I won't be able to assist with. ",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/132208/original/debugging/debug-your-c-sharp-net-java-or-php-program.jpg",user_id=72,category_id=3,service_language_id=13,web_package_id=15)
    service_71=Service(publish=True,title="I will fix all wordpress, woocommerce, magento, php and html errors",description="Having Advanced Programming Skills and Hardworking Mentality plus a history of being an effective developer to provide optimal solutions to the problems with Websites, WordPress Websites, eCommerce and WordPress WooCommerce stores. This gig includes: ◈ Website Development and Fixes (HTML, CSS, PHP) ◈ PHP Errors fix ◈ Website Speed Optimization ◈ WordPress Website Development ◈ WordPress Customization and Optimizations ◈ WordPress Plugin Development ◈ WooCommerce Shipping Plugin ◈ WooCommerce Error fix ◈ Payment Gateway issues fix ◈ CSS and responsive design issues ◈ Magento ( Shipping extension development for 1.x & 2.x ) ◈ Debugging proficiency ◈ Code validation skill Being an entrepreneur, I comprehend the Importance of your business. By remembering that, I ensure that I esteem your Time and Cash, as much as I can. On the off chance that I take an Order, It's my obligation to give a Quality Service. I've done long periods of research on multiple Web Programming Tasks & I'm an Expert at what I do. Talking about the issue with me in inbox & getting a Custom Offer is vastly improved and acknowledged than making an Order legitimately. ",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/142052021/original/0d5c4cb89bd7a8bfeb02665d53a589b63284b68d/fix-all-wordpress-woocommerce-magento-php-and-html-errors.jpg",user_id=73,category_id=3,service_language_id=6,web_package_id=16)
    service_72=Service(publish=True,title="I will fix wp error, wordpress, debug, theme,template, issue",description="I have completed more than 1000 jobs and 400 jobs with 100% positive feedback having experience of 10 years.  My experiences allow me to quickly and effectively troubleshoot any issue like debugging and fix WordPress theme or plugin error, fix plugin conflict etc. I can help you to fix : # White Screen of Death error # Fix WordPress error (CSS, HTML or PHP, JQuery issue) # Site migration one host another host # Fix WordPress Theme # Fix Plugin issues # Fix bug from installed plugins # Fix slow loading website # Removing malicious script # Fix any PHP error # Adding new functionality with PHP work Everything related to WordPress could be done here! So, what are you waiting for? If you need any special requirement please discuss before purchasing the gig. Contact NOW, with your details! ",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs2/2821151/original/eaa74e905d1cc2ba23fcb5abc4f26eaee233ebb2/fix-your-wordpress-site-error.jpg",user_id=74,category_id=3,service_language_id=3,web_package_id=17)
    service_73=Service(publish=True,title="I will fix html, css, bootstrap, responsive bugs, issues",description="Contact me before placing the order. Spend more time in building great website and less time dealing with bugs :) I'll fix all HTML, CSS, responsive and bootstrap related issues. What I Offer: HTML/HTML5 Bug Fixing. CSS/CSS3 Bug Fixing. Fixing Bootstrap issue. Fixing Responsive issues. Bootstrap3 to Bootstrap4 conversion. Layout Changes/fix. Style Changes/fix. Making Responsive Layouts/Elements/Navigation/ Mega Menus Work related to JavaScript / jQuery (e.g Sliders, Tabs, Gallery, LightBox, etc) Adding working contact form Cross Browser Compatible w3c Validations RTL version Email Signature I can also convert PSD to HTML. If you want to develop your site from scratch, contact me. You can check my other gigs too. ",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/99988134/original/61d4dfc770b9720ed79ec7df203d09740f6b6109/fix-html-css-responsive-issues.jpg",user_id=75,category_id=3,service_language_id=3,web_package_id=18)
    service_74=Service(publish=True,title="I will fix any kind of issue on your server or website",description="I can fix any kind of issue associated with your server or website such as : CPanel / WHM Errors Apache Errors PHP Errors DNS Issues SMTP / Postfix Issues Errors / Issues with Scripts & Online Stores Issues with MYSQL Issues with WebOS Issues with WordPress And Many More............ I am available 24/7, so I’ll do the job ASAP. 100% Satisfaction is Guarantee. If you are not satisfy with my service, I'll completely refund your money. Note that => 1 Gig = 1 Task Important: In order to avoid misunderstanding, please contact me before ordering the Gig. Have any questions or need another service? Feel free to contact me. Just take a look at FAQ section Thank You ",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/101218519/original/34b9809c278956abfae0d03ff33ca0a9f67ab47a/fix-any-kind-of-issue-on-your-server-or-website.jpg",user_id=76,category_id=3,service_language_id=6,web_package_id=19)
    service_75=Service(publish=True,title="I will be your codeigniter, laravel, core PHP expert",description="If you are facing trouble in Codeigniter. Not able to catch the bugs or blunder/error? Leave it to me! I will fix your bugs and furthermore demonstrate to you what the issue was....!  - Codeigniter/Laravel bug and mistakes  - Css issue  - jQuery issue.  - Javascript issue.  - Html issue  - Database issue,  - HTML customization.  What I am Offering:  Install Any Application  E-commerce Cart Portal Development Responsive designing.  Customize Web App Development  Enrollment/subscription login/registration based site  The executives System Web Applications like (Restaurant,Hotel,Shop,Point of Sale,Inventory and Employee Management System) and some more  Electronic ERP  Fix Security and Performance issue.  Laravel Custom Website  Bug-fixing and investigating  Installment entryway framework.  ________________________________________  Why me?  100% Satisfaction with numerous updates  100% Readable, Commented and Clean code.  Quick conveyance.  ___________________________________  Note: Please Contact Me Before Ordering Programming Language PHP Expertise PSD to HTML Performance Design",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/133662748/original/9cb7a64a63ebfe38c915e8427e49e4538b657d80/be-your-codeigniter-laravel-core-php-expert.jpg",user_id=77,category_id=3,service_language_id=4,web_package_id=20)
    service_76=Service(publish=True,title="I will install, develop, fix or amend php, laravel",description="Some times after upload or migrate a laravel application to server it's not working due to many reasons i will investigate and solve those problems   I guarantee  100% Security of your Information 100% Customer Satisfaction ----PLEASE CHAT WITH ME BEFORE ORDER----- Programming Language PHP",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/113618904/original/148581c01dd04105ca0cb247cc6c0e64993383ee/fix-your-laravel-issues.png ",user_id=78,category_id=3,service_language_id=6,web_package_id=21)
    service_77=Service(publish=True,title="I will fix your wordpress, php, html, jquery, css, database bugs",description="*** Message me with a detailed problem description before ordering. *** will fix WordPress / php / database / html / css / jQuery bug in your webpage. Delivery time and cost varies based on the problem. Generally, a css issue can be resolved within minutes and cost only $5. Thanks! Programming Language HTML & CSS Expertise Cross Browser Compatibility W3C Validation Design",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/73056151/original/132a4a7b7f830511b4692fc786ccd9ccdb80c52a/fix-your-wordpress-php-html-jquery-css-database-bugs.jpg",user_id=79,category_id=3,service_language_id=3,web_package_id=22)
    service_78=Service(publish=True,title="I will edit html and css on your webpage",description="I can alter the look of the element like size, font, margin, color, padding, and general style changes that are not included in WordPress theme options panel or on plain Html CSS based webpages! I can also make relevant changes to the HTML of the page! I can also provide these services for static HTML pages, Joomla , Magento , Prestashop, and Shopify. Please contact me before ordering to check the feasibility and to get an accurate quote. Thanks for your support :) Looking forward to working with you. Message me to get started. Programming Language HTML & CSS Expertise PSD to HTML Performance W3C Validation",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/116856649/original/a5945e0c694538f4e36215017d623873aac3ce67/edit-html-and-css-on-your-webpage.png",user_id=80,category_id=3,service_language_id=3,web_package_id=23)
    service_79=Service(publish=True,title="I will edit html and css website professionally",description="-------------------- Special New Year 2021 Offer ------------------- Do you have problems with your HTML, CSS or JavaScript code? Your Bootstrap is not as responsive as expected? Or you just want something new added to your website? Want to edit wordpress? No problem ! Hire me! I will assist you with any HTML / CSS issues or bug fixing. The code will be professionally written and easy to maintain. I will develop your website responsive, it means it will work on all major devices like mobile, desktop and tablet.  Make your web-page user-friendly and mobile friendly. Fix website layout. Get your HTML and CSS bugs fixed in shortest time! Why would you hire me? I will do my best to provide highest quality possible in shortest time. Free Extras:  ASAP Delivery Unlimited revisions  100% money back if not satisfied.  *Please message me once before ordering. Programming Language HTML & CSS Expertise Cross Browser Compatibility PSD to HTML Design Do you have problems with your HTML, CSS or JavaScript code? Your Bootstrap is not as responsive as expected? Or you just want something new added to your website? Want to edit wordpress? No problem ! Hire me! I will assist you with any HTML / CSS issues or bug fixing. The code will be professionally written and easy to maintain. I will develop your website responsive, it means it will work on all major devices like mobile, desktop and tablet.  Make your web-page user-friendly and mobile friendly. Fix website layout.  Get your HTML and CSS bugs fixed in shortest time! Why would you hire me? I will do my best to provide highest quality possible in shortest time. Free Extras:  ASAP Delivery Unlimited revisions  100% money back if not satisfied. *Please message me once before ordering.",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/108821954/original/fa2ca4fbe7402caf96ff2b9a3d8f8afd6a78644a/edit-html-and-css-website-professionally.jpg",user_id=81,category_id=3,service_language_id=4,web_package_id=24)
    service_80=Service(publish=True,title="I will fix, install and develop php laravel websites",description="I will fix, install and develop php laravel websites",listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/124686939/original/0c50460b3406487ccc988223ab975ae0dcd7748b/fix-install-and-develop-php-laravel-websites.jpg",user_id=82,category_id=3,service_language_id=6,web_package_id=25)

    db.session.add(service_56)
    db.session.add(service_57)
    db.session.add(service_58)
    db.session.add(service_59)
    db.session.add(service_60)
    db.session.add(service_61)
    db.session.add(service_62)
    db.session.add(service_63)
    db.session.add(service_64)
    db.session.add(service_65)
    db.session.add(service_66)
    db.session.add(service_67)
    db.session.add(service_68)
    db.session.add(service_69)
    db.session.add(service_70)
    db.session.add(service_71)
    db.session.add(service_72)
    db.session.add(service_73)
    db.session.add(service_74)
    db.session.add(service_75)
    db.session.add(service_76)
    db.session.add(service_77)
    db.session.add(service_78)
    db.session.add(service_79)
    db.session.add(service_80)

    db.session.commit()


# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and resets
# the auto incrementing primary key
def undo_services():
    db.session.execute('TRUNCATE Services RESTART IDENTITY CASCADE;')
    db.session.commit()
