from app.models import db, Service


def seed_services():
    service_1 = Service(title="I will do web apps with PHP and mysql professionally", description="***ALWAYS DISCUSS FIRST BEFORE MAKING ORDER*** ***ALWAYS DISCUSS FIRST BEFORE MAKING ORDER*** ***ALWAYS DISCUSS FIRST BEFORE MAKING ORDER*** Hello Fiver I am Anas From Pakistan a nation of web developers! I am here to do all works regarding web developments,php,mysql,web apps and whatever you want. I have experience of doing big projects so just contact me i will never disappoint you and full fill your requirements professionally. I CAN DO : 1.Php Scripts. 2.Php With Mysql. 3.Web apps. 4.Web desiging. 5.Fix your php Scripts. and lots of more just contact me.",
                        listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/105267010/original/f1522fe650f34fda57b7bfd47106cce385d24af6/do-web-apps-with-php-and-mysql-professionally.jpg", user_id=3, category_id=1, service_language_id=6, web_package_id=1)
    service_2 = Service(title="I will build web app for you", description="I will develop an awesome responsive web app from scratch for you. If you have a legacy website / web application or an exciting idea and you want a modern, responsive, scalable web application that can be easily accessible from anywhere, whether from phone or desktop, then this gig is perfect for you! Gig components : Responsive web app Any modern browser compatibility Clean maintainable code Live preview before delivery Skills: Vue.js, React.js, Nuxt, Laravel, Node.js, Express, MongoDB, MySQL, Firebase, PWA (Progressive Web Apps), SSR, SPA (Single Page Application) Kindly message me before placing an order, I respond quickly!",
                        listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/105267010/original/f1522fe650f34fda57b7bfd47106cce385d24af6/do-web-apps-with-php-and-mysql-professionally.jpg", user_id=4, category_id=1, service_language_id=4, web_package_id=2)
    service_3 = Service(title="I will create web gis application using cesium, arcgis, mapbox", description="I offer a professional service to develop a 2D or 3D WebGIS or WebMap application for your custom requirements. My service includes a complete system infrastructure that includes data integration and pre-processing, geodata analytics, geodata visualization, and application deployment. About me: I'm Joe, a Geospatial Scientist with more than ten years of experience in the GIS field. My daily work includes developing and researching GIS Analyst and Automated Workflow in various projects for many clients. I am an expert in several GIS Tools, frameworks, and APIs including CesiumJS, ArcGIS, QGIS, FME, Deckgl, Here MAP, OSM, PostGIS, Google Map, Mapbox, etc. Example WEB GIS: >> Web Application for Construction Planner >> Web GeoPortal with GeoProcessing Tool >> 3D Building Model Web Viewer (glTF, 3D Tiles, i3s) >> 3D Real Estate WebMap >> 3D Route Tracking/ Routing API integration Free consultation: Feel free to message me your requirement, and we can discuss the process and work through your project together. ",
                        listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/183875998/original/1e5c468307cb253baed38dd5bbdb90b24f23a161/create-a-3d-web-application-with-cesiumjs.jpg", user_id=5, category_id=1, service_language_id=1, web_package_id=3)
    service_4 = Service(title="I will develop and design fully responsive web applications", description="Hello,I can design and develop simple landing pages to full fledge web applications. My expertise are in front-end and back-end development using modern technologies like: Angular React Material Ui Bootstrap Redux Flex I can develop web applications with the features like: Responsive design Progressive Scalable Social media integration Payment method integration and many more. Please feel free to ping me at any time.",
                        listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/140492917/original/488321ca7de2e53c778ed4a89ceb77a414a05195/develop-and-design-fully-responsive-web-applications.png", user_id=6, category_id=1, service_language_id=4, web_package_id=4)
    service_5 = Service(title="I will create bep20 token on binance smart chain", description="I will create and deploy your own Bep-20 Token On Binance Smart Chain with all standard functions of smart contract. Token Features: Transferable Tradable Mintable Burnable Secure Verified Contracts You can list and Trade it on any exchange What will you get : Bep-20 Token Development on Binance Smart Chain Deploy in Binance Smart Chain Verify Your Token on Binance Smart Chain **GAS FEE NOT INCLUDED** PLEASE FEEL FREE TO MESSAGE ME BEFORE PLACING AN ORDER. ",
                        listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/198800590/original/5f0e78d5e7ccedae9b3a70baea7d7001303f21b9/create-bep20-token-on-binance-smart-chain.png", user_id=7, category_id=1, service_language_id=1, web_package_id=5)
    service_6 = Service(title="I will help you with twilio solutions in your project", description="I'm a Twilio Champion Contact me before ordering I can help you with Twilio, setting an API system for your SMS, Voip or Voice solution, integrate it with Zoho or any other CRM you have. Here a list of the most common integration I can build: Twilio SMS Twilio Bulk SMS Twilio Voice Call Twilio Call Forwarding Twilio Lookup API Twilio IVR Studio Twilio Call Recording Twilio SMS Forwarding  Twilio Voicemail ( with email forwarding Twilio SMS Autoresponder Twilio integration with Google Sheets Twilio / CRM integration Twilio Flex Twilio Pay Twilio IoT Twilio Whatsapp Twilio Authy And much more  I can also work with any other kind of API integration you need. I already built many integrations also with Intercom, aWeber, Zoho, Zapier, Facebook, Twitter, Podio, Google API, etc. Other than Twilio I can also help and work with you implementing MessageBird solutions. Let me know what exactly you need and I will be glad to help you. ",
                        listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/57188349/original/c25b35a54e3895e50ebc87a2425fb9a8ffe3782a/help-you-with-twilio-api.jpg", user_id=8, category_id=1, service_language_id=1, web_package_id=6)
    service_7 = Service(title="I will write custom PHP script, php code", description="I am a Full Stack Web Developer having years of experience in Web Development. I have a great grip on PHP and can solve every problem related to Core PHP. If you have any problem related to your PHP script then you are at the right place.I will do:Refactoring your existing codeForm Validations on the server-sidewrite a custom PHP scriptbug fixingOr anything related to PHP codeI will do your work until you are satisfied.Note: Please message me before placing your order to estimate the Project amount and send you a custom offer.Thank You.",
                        listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/143775684/original/98e6bc5852ef07ebb61797808479d4f328697050/write-custom-php-script-php-code.png", user_id=9, category_id=1, service_language_id=6, web_package_id=7)
    service_8 = Service(title="I will code anything in ruby on rails", description="Please Contact me before placing the order. Looking for a top notch Ruby on Rails Engineer? Yes You are on right place. Why me? Level 2 Seller Ruby on Rails Expert 4 years of Professional Experience Reliable Fastest Delivery What Services I Provide? Rails Installation / Configurations ( Remotely ) Rails Tuition Classes Any Bugs / Errors / Code Reviews Gems Installation Any Ruby Script Web Development in Rails Web Services Web Designing (HTML, CSS, BOOTSTRAP, JQUERY & JAVASCRIPT) Web Servers ( Puma, Webrick, Nginx and UniCorn ) Deployment ( Heroku, Digital Ocean, Amazon S3 ) If you have any questions and need any help, You can ask me about anything anytime, I also give free assistance to rails students. thanks bilal5110 ",
                        listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/18130029/original/0dc18ae753687c1e7dfb35f5059488919205650d/code-for-you-in-ruby-on-rails.jpg", user_id=10, category_id=1, service_language_id=3, web_package_id=8)
    service_9 = Service(title="I will create website, debug, fix PHP scripts for you", description="Please ask for my availability before placing an order. This gig is solely for PHP Scripting. Aside from PHP scripting I also offer other services(w/c I will post as a new gigs soon) which can be writing from scratch, debugging, and testing the codes.I have full knowledge with the ff. programming tools and concept: Javascript  JQuery  CSS  HTML 5  PHP Frameworks (Laravel, CodeIgniter). Custom PHP Framework or coding from scratch Repositories (Github and Subversion). IMPORTANT NOTE: After order completion there will only be 4 days of free support for the related task/project. IF any bug, modification or additions it will be subject to a new gig already so please test it within the time period. Any orders/ question message me and let's have a nice talk. All inquiries are welcome. Thanks! ",
                        listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/5226061/original/raw2/write-debug-fix-php-scripts-for-you.JPG", user_id=11, category_id=1, service_language_id=3, web_package_id=9)
    service_10 = Service(title="I will build online academy like udemy,kajabi,thinkific,teachable", description="Online School / Academy Worldwide Selling Web Consulting Service WHAT do I OFFER? More than 150 languages translator on real-time Premium look 100% Responsive Interactive layout Up to market standards 100% as per your requirements Valued experience developing Online Academy applications Pre & Post sale support and design alteration  Quality & professional work  Unit testing  Modules Included? Teacher Students Courses Admin  1 - Teacher Module Tacher Sign Up Teacher Login  Teachers Capabilities Teachers Dashboard Teachers Capabilities 2 - Students Module Students Sign Up Students Login  Students Enrollments Students Dashboard 3 - Courses Module Courses publishing Courses Name, Description, Why to take, Targeted audiences & many more Quizzes  Final Tests Checkout / Purchasing via supported methods like Pay-Pal / CC or any other required 4 - Admin Module Teachers Manager User-friendly Admin Dashboard TO manage on your own as well Courses Manager Students Manager Complete Access To Each Corner Of Website SIMILAR PROJECTS DONE :  https://academy.efixed.co/ https://www.cubeacademy.io/ http://eclipps.co/ https://brainowconsulting.com https://academy.lashesnskinbydaphne.com/ ", listing_img="https://fiverr-res.cloudinary.com/videos/so_1.121148,t_main1,q_auto,f_auto/akvdjnilvc9erqr8f50g/develop-online-academy-or-school-like-udemy-or-lynda-for-you.png", user_id=12, category_id=1, service_language_id=1, web_package_id=10)
    service_11 = Service(title="I will automate a business process using zapier", description="Zapier is a tool which allows hundreds of different web apps to communicate and collaborate with each other. It can be used to speed up and automate your business workflows and processes in an infinite number of cool ways. You tell me what part of your business you want automated and I'll do it with Zapier. The apps Zapier support out the box are listed in the App Directory on Zapier. These can be tied together in pretty much any combination, using the various triggers/actions listed on the app page. Even if the app you want to automate is not listed, or the required trigger/action doesn't exist, there is still a possibility I can work some magic for you using webhooks and/or custom code steps. If you don't know what's possible, book the consultation step, tell me your idea and I'll research what's possible. ",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/101029300/original/46e3d308d94e03fda8458cff3e04f41c4661c700/automate-a-something-for-you-by-connecting-2-apps-on-zapier.png", user_id=13, category_id=1, service_language_id=1, web_package_id=11)
    service_12 = Service(title="I will create top level erc20 token on ethereum blockchain", description="UPDATE: Due to the increasing gas fees on Ethereum, I can no longer afford to include the smart contract creation fee in my gig price.For 100$ (plus extras if you are interested) I will create the coolest thing in tech nowadays: your very own TOP-LEVEL customised ERC20 Token.   What exactly can you do with an ERC20 Token?  You can do many great things, and just to name a few: you can trade it on Exchanges (I can help you with that - see my Gig Extra), you can start your own ICO/IEO crowdsale and sell tokens to anyone interested or you can simply use it for developing your own projects. How awesome is that?  What I need from you: Token Name (ex. CARDANO) Symbol (ex. ADA) decimals: (18 is standard, 0 means your token is not divisible)  Free Bonus: If you purchase my gig, I will send you the source code in a separate file and I will verify the token’s contract source on etherscan.io, both free of price. So how come the price is only 100$?  I think 100$ is a fair price for this gig. But if you think it’s worth more, feel free to send me a tip, I won’t mind at all. If you have any questions, please contact me. ",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/107236646/original/73020f650d72fe1b187a6335510645900d3e0999/create-your-erc20-token-on-ethereum-blockchain.png", user_id=14, category_id=1, service_language_id=1, web_package_id=12)
    service_13 = Service(title="I will do PHP,MySQL,Javascript development or bug fixes", description="I am an experienced PHP/MySQL developer. This gig covers one of: tracking down and fixing 1-2 bugs in your PHP/Javascript code debugging 1-2 performance problems in your MySQL database adding a PHP/Javascript feature or script making a change to your MySQL database (adding a new table for example) Generally speaking, these items will take one (possibly two) hours to complete. Please contact me for adding features and database design. ",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/6334721/original/working/do-php-mysql-javascript-development-or-bug-fixes.PNG", user_id=15, category_id=1, service_language_id=6, web_package_id=13)
    service_14 = Service(title="I will develop custom php web application, website", description="Hello,This Gig is all about the best Quality PHP products. If you are looking for custom responsive website or web application then you are at right place. I will develop custom web application and website for you.  I am a professional full stack web application developer with professional experience of almost 5 years. I have developed many web application and website in recent years. I'm promised to give 100% satisfaction to my clients.  My skills: PHP, Laravel, HTML, CSS, Bootstrap, javaScript, jQuery, mySql, API You'll get: Modern, responsive, secured, quality system with good coding structure. Feel free to contact me to know more about my works. ",
                         listing_img="https://fiverr-res.cloudinary.com/videos/so_0.971855,t_main1,q_auto,f_auto/uy3omkufgckw3cdok2lm/develop-website-and-php-web-application.png", user_id=16, category_id=1, service_language_id=6, web_package_id=14)
    service_15 = Service(title="I will do javascript html css jquery task", description="Are you stuck trying to add a new feature or design element on your website? Or just want someone to handle the entire job for you while you relax, here's what I'm offering! ➤ Work on Javascript to add new features or fix JS Bugs. ➤ Fix performance issues. ➤ Write HTML5 / CSS3 codes and fix any bugs. ➤ Do any JQuery task or just use Vanilla Javascript (As required). ➤ Do tasks related to web designing or some functions. ➤ Make website responsive or fix responsiveness issues. ➤ Add new CSS elements and designs. ➤ Third-Party API Integration. I can write scripts for specialized platforms likes: ➤ ClickFunnels ➤ WordPress CMS, WordPress themes ➤ kvCore website customization What to expect when hiring me? ✔ Robust and effective communication ✔ Results better than expectations ✔ Work delivered ON TIME! ✔ Flexible work timings that suit my clients I Would love to discuss your project with you in more detail. Send me a message now to get started. ",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/148484167/original/003156699152e1dc6ca7c8156d68ad53efad878e/do-javascript-html5-css3-jquery-bootstrap-task.png", user_id=17, category_id=1, service_language_id=4, web_package_id=15)
    service_16 = Service(title="I will install any PHP script on your hosting or vps server", description="Ahoy,This is M. Hamza Iqbal from Pakistan, Through this GIG I will install PHP Script on your hosting or server. So you have bought a script from codecanyon or from any other platform and looking for somone who can install and modify that script, then you are at the right place, Order me here I am expert in doing this. Not only installation but also If you want any kind of modification then you can contact me as well. Please Note: Always contact me first before placing the order. If you want me to upgrade the preinstalled script then please first show me your current website and the script you want me to upgrade. ",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/138701201/original/b0871becb969fba7965eb1ba4731fc8563d3eba3/install-any-php-script-on-your-hosting-or-vps-server.jpg", user_id=18, category_id=1, service_language_id=6, web_package_id=16)
    service_17 = Service(title="I will create any web calculator for wordpress and any website", description="I have an experience of 5+ years on web design and development. I have experience in building any sort of custom calculator for WordPress site. I can design and develop following online calculators for your website: I can do: Finance Calculators Roi Calculators Mortgage Calculators Excel to web conversion Fitness Calculators iframe based calculators Health Calculators Custom Calculators Clone online calculator WordPress calculator Send result to the user via E-mail Graph Calculators The print result or export result as CSV, PDF and Excel Sheet etc Database Integration Clone online calculator Bug fixing in the calculators Please inbox me before order. Compatible with: Web, Wordpress, SquareSpace, Drupal, Shopify, Magento and so on. My Special Offers Unlimited Revisions work until you fully satisfied Free small changes in future Your form/calculator will be: 100% responsive User friendly SEO friendly Bug free If you have any question, don't hesitate to ask me. Best Regards Abdullah ",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/182329724/original/022435cfe1738e3243e5e0110168ce24d30bb60d/create-any-calculator-for-your-wordpress-and-any-website.jpg", user_id=19, category_id=1, service_language_id=3, web_package_id=17)
    service_18 = Service(title="I will help you with a javascript, html, and css project", description="Please contact me before purchasing an order so we can discuss your project and how to make it happen. In your message, try to include: 1. The problem(s)/frustration(s) that you'd like to resolve. 2. The value that would be gained from resolving them. 3. What you'd like me to do to help you resolve them NOTE: I AM A TECHNICAL EXPERT, NOT A DESIGNER. I can receive a design and turn it into code, but I am not as proficient when it comes to creating an aesthetic designs from scratch. In other words, I can easily make pretty things functional, but I am not as good at making a functional thing pretty. Have an idea for a web project or a want to add a new feature to what you have already? How about a script you just need to work a little differently. Got some HTML/CSS/JavaScript that is giving you a headache? I will help you with almost any HTML/CSS/JavaScript project. I have helped people with: Custom tools and full-stack web apps; redesigning their code to be simple, easy to follow, future-proof, and safe; modifying PHP code; scripts to fix bugs; tutoring; debugging; and other tweaks to take their websites to the next level of functionality. ",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/112807779/original/3c524085bcac24936885295b24cdc0c2814250da/create-a-small-to-medium-javascript-web-app-for-you.png", user_id=20, category_id=1, service_language_id=3, web_package_id=18)
    service_19 = Service(title="I will add google map with dynamic markers and search", description="I am a professional software developer. I have 7 years of experience as a software developer. I have worked in ASP.Net web forms, ASP.Net windows forms, ASP.Net MVC, WCF, jQuery, Ajax, Android and Cordova/PhoneGap. Contact me if you need professional programming. In this Gig I will add google map to your web page. It can be a static page or dynamic (with PHP or ASP.Net). It will have the following functionalities. Get markers data from database with jQuery ajax and display on the map. Add search box and display location in the map. Add or remove markers from the map and save the data back to database using ajax. I can do any Google Maps API relevant work, like: Displaying KML files. Creating/generating KML files. Using the GeoXML3 library. Using the drawing library (drawing polygon, polyline, circle or rectangle). Adding autocomplete (a location search box). Using places library. Using the directions API. Adding clusters. Adding google map to PHP, .Net (MVC or Web Forms) or Android app (native or cordova/phonegap) applications. Please see below YouTube channel for some of the work we have done. https://www.youtube.com/channel/UCkSqn5WOF6Rof0BD_PnPHlw ",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/36113710/original/b62ef9a0eb4ab97aebb099e891af37f6745cb212/add-google-map-with-dynamic-markers-and-search.png", user_id=21, category_id=1, service_language_id=2, web_package_id=19)
    service_20 = Service(title="I will supply a complete content management system", description="- Content Management System - SSL certificate (For site Security and Form Submissions) - Hosting on World-Class AWS - On-Page editor for quick changes to text - Form Management Area (Download all Form Data Instantly) - GDPR Compliant Form Server",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/165716320/original/e7dfbd0fa285c1607b79cccf02d7bbe9a29c97b4/supply-a-complete-content-management-system.jpg", user_id=22, category_id=1, service_language_id=1, web_package_id=20)
    service_21 = Service(title="I will develop website using php, yii, yii2, codeigniter, laravel", description="Hello,Greetings of the day.  I am a full stack PHP developer, and have 10+ years of experience in web development, web app development.  are you looking to create a website, web application, fix any issue, bugs to on your website? then you are at Right GIG. Services: PHP  Yii  Yii2  CodeIgniter (CI) Laravel  SQL / Database SAAS CRUD API development / Third party API Integration (Google, Facebook ) Payment Gateway Integration (  PayPal, Stripe, and many more.. ) Codecanyon Scripts Integration JavaScript, Jquery, Ajax Website Speed Optimization Bug fix Social Media Login LMS  Food Delivery Applications   PHP Developer, Yii Developer, Yii2 Developer, CodeIgniter Developer (CI), Laravel Developer  also, I have expertise in Karenderia Multiple Restaurant System (KMRS online food ordering system), Kartero for food delivery. Karenderia Mobile app, Karenderia Driver app, Karenderia Merchant app, Karenderia user app Please discuss before ordering to make a job 100% success.  Thank you!",
                         listing_img="https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/114465392/original/9721e378413d4516630f7f58593fa55547458cb7/develop-website-web-app-using-php-laravel-codeigniter-yii.jpg", user_id=23, category_id=1, service_language_id=6, web_package_id=21)
    service_22 = Service(title="I will create any calculator for your wordpress and non wordpress", description="I will create any online calculator for your wordpress and non-wordpress site (wix, squarespace etc) !!!Please contact me before placing the order. We will discuss all the details and you will get a calculator that fully meets your needs and at a fair price!!! !!!Please contact me BEFORE to order, for better execution of job.!!!  Please contact me for examples of previous works You'll get :   - Custom design of calculator - User friendly interface - Responsive design - Mobile optimization - Source code - My support - Images integration - Chart/graph  - Result of calculation to email  - Shortcode for wordpress - Wordpress plugin for your wordpress site - Options page - 100% free minor changes in the future I use: javascript, jquery, css, html, php !!!Please contact me BEFORE to order, for better execution of job.!!! ",
                         listing_img="https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/79756516/original/1260a98cfd3c620bd59af088d9822e54ba5b7452/create-any-calculator-for-wordpress.png", user_id=24, category_id=1, service_language_id=1, web_package_id=22)
    service_23 = Service(title="I will develop website using PHP, codeigniter, laravel, wordpress", description="Available now for taking new orders! If you are looking for a Web Team who is dedicated and an expert in PHP, LARAVEL, CODEIGNITER, VueJs, WordPress then you are at Right Gig. we have extensive experience in web development, web app development and we can get you a professional website from scratch by using PHP, Laravel, Codeigniter, and WordPress. Also, if you are facing any issues on your website? leave it on us! we will fix your bugs and also show you what the problem was.! Services offered in this gig: PHP  Laravel  CodeIgniter (CI) SQL / MongoDB SAAS Develop a complete website from scratch Add New features Fixing bugs from your existing script Upgrading to the latest version Payment Gateway Integration ( PayPal, Stripe, and many more.. ) Website Speed Optimization Website On-page SEO Optimization Code Canyon Scripts Integration & Modifications Social Media Login ★•••★ I turn your ideas and dreams into working software ★•••★ Please discuss before ordering to make a job 100% successful.  ⚠️ Don't apply to hire us regardless of the quality of the results if you are looking for the cheapest developer(s). Thanks  Regards  Rashid Ashraf & Team",
                         listing_img="https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/109116477/original/ffbd2add5958318a547ff782f1523d59bf253469/fix-any-issue-or-create-php-codeigniter-website.png", user_id=25, category_id=1, service_language_id=6, web_package_id=23)
    service_24 = Service(title="I will create interactive data visualizations with d3", description="Please contact me before ordering with your project description so I can assist you according to your specific needs. I stumbled upon data visualization while working as a physicist, and I've been passionately distilling insights from data and communicating findings with the superpower of visualizations ever since. I will be your invaluable resource for: You want to transform your data into Accurate, Straightforward and Aesthetically Pleasing visualizations (I call them my ASAP standard) on the web. Let me help you with that! If you have data, I can assist you to choose the right chart type to achieve your visualization goal. If you have a mockup, I can code up the visualization according to your mockup specification. If you have a chart already, I can help redesign and improve the chart with more appealing aesthetics and more engaging user interactions. If you have any other requests, no matter it is a static figure or an interactive webpage, I am happy to discuss your project details with you.  I am looking forward to working with reliable and trustworthy clients just like you. If you have any questions or requests, please click the 'Get a Quote' to contact me!",
                         listing_img="https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/105634882/original/a919c05027bdf6fa3a27de8f5c6b8427d012f36e/create-interactive-attractive-and-informative-d3-charts.png", user_id=26, category_id=1, service_language_id=1, web_package_id=24)
    service_25 = Service(title="I will build a custom monday app ", description="It must be irritating, right? Getting bombarded by messages from people that tell you they know how to build your product properly, but they actually don't. Let me be candid with you: I've been there too. Most service providers focus on just technical stuff. Oh, you want an API? Yes, I can build the integration for you. Oh yes, and I can also create a video, and actually everything, just put an order on Fiverr! No! I want you to understand my business idea, so you can help me find the best solution to my users' problem! Sounds familiar? Now, let me cut through the noise and quickly introduce myself: My name's Vladimir, I help entrepreneurs like you build custom Monday Apps. I focus on helping YOU solve the problem of your users. I speak your language: You don't need to try and pretend you know everything about APIs, integrations, all these boring things. The technical part is on me. I just need your creative vision to implement the idea into life. Before my Gig gets PACKED with orders again, drop me a line about your project.",
                         listing_img="https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/206745906/original/7e5d9e63ad19628bcb56875d2067344862afb085/build-a-custom-monday-app-033b.png", user_id=27, category_id=1, service_language_id=1, web_package_id=25)
    service_26 = Service(title="I will do custom web development ", description="Businesses that use complex software are often started by visionaries with experience in niche industries.  You’ve likely succeeded by creating products or services that resonate with your audience, rather than learning technical details or graphic design standards. At the same time, hiring and managing employees with skill sets beyond your own expertise can become a real nightmare. Save time and money by outsourcing design and technology implementation of your web applications. Developing solutions that bring results is real art.  That is why our team consists of dedicated experts only.  All of them are experienced professionals with a deep understanding and passion for their craft. Here are a few of the ways we can help you keep your website running smoothly: Backups and Recovery Security Patch Implementation Performance Optimization Bug Fixes Design Changes & Improvements New Website Pages Content Updates Tutorial Videos SEO Improvements Hosting Updates Platform-based Updates Consulting Calls Sounds like a good fit? Contact me today to discuss your site and start getting results.", listing_img="https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/126118509/original/64f91de4368b2bd07b40f86bb13d15aa3c518a3e/do-custom-web-development.png", user_id=28, category_id=1, service_language_id=3, web_package_id=26)
    service_27 = Service(title="I will create online calculator or form for your wordpress or any website ", description="You need custom form integration or custom calculator on your site? I'll help you. Form or calculator can be integrated with database, pdf export or html Email for results export. I can provide solution for any requirement.  If you use WordPress - I can offer shortcode integration or custom WordPress plugin. Your form/calculator will be: ✔ 100% responsive ✔ User friendly ✔ Bug free ✔ SEO friendly Before the order we'll discuss: ✔ Mockup/design of your form ✔ Behavoiur an calculation rules ✔ PDF/EMAIL/CHARTS ✔ price and delivery time Price starts only from 50$ (form up to 5 fields, calculator up to 5 dependencies and formulas). Having 8+ years of experience in web-development (php/js/html5/css3), I'll suggest the fastest and clean solution.",
                         listing_img="https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/108156566/original/c074ec03ef525f41d8cd5b451e1f9aa8ecba749d/create-custom-js-calculator-or-form-on-your-site.jpg", user_id=29, category_id=1, service_language_id=1, web_package_id=27)
    service_28 = Service(title="I will install, setup and customize erpnext for you ", description="I am an experienced Python and ERP developer having 6+ years of experience. I will customize erpnext to any level and to any extent from the latest version installation to print and form customization and to new module and app development. I can also provide training to use ERPNext ",
                         listing_img="https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/139021752/original/0234be722829b4f4a60b66b55b3cd9192db32480/install-setup-and-customize-erpnext-for-you.jpg", user_id=30, category_id=1, service_language_id=7, web_package_id=28)

    db.session.add(service_1)
    db.session.add(service_2)
    db.session.add(service_3)
    db.session.add(service_4)
    db.session.add(service_5)
    db.session.add(service_6)
    db.session.add(service_7)
    db.session.add(service_8)
    db.session.add(service_9)
    db.session.add(service_10)
    db.session.add(service_11)
    db.session.add(service_12)
    db.session.add(service_13)
    db.session.add(service_14)
    db.session.add(service_15)
    db.session.add(service_16)
    db.session.add(service_17)
    db.session.add(service_18)
    db.session.add(service_19)
    db.session.add(service_20)
    db.session.add(service_21)
    db.session.add(service_22)
    db.session.add(service_23)
    db.session.add(service_24)
    db.session.add(service_25)
    db.session.add(service_26)
    db.session.add(service_27)
    db.session.add(service_28)

    db.session.commit()


# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and resets
# the auto incrementing primary key
def undo_services():
    db.session.execute('TRUNCATE Services RESTART IDENTITY CASCADE;')
    db.session.commit()
