"""empty message

Revision ID: 44e15c64a3c9
Revises: cea3dc676a1e
Create Date: 2021-06-02 19:58:02.272280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e15c64a3c9'
down_revision = 'cea3dc676a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Webs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('delivery_time', sa.Integer(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('design', sa.Boolean(), nullable=False),
    sa.Column('content_upload', sa.Boolean(), nullable=False),
    sa.Column('source_code', sa.Boolean(), nullable=False),
    sa.Column('revisions', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Webs')
    # ### end Alembic commands ###
