"""empty message

Revision ID: 374f1afc69e5
Revises: 44e15c64a3c9
Create Date: 2021-06-02 20:00:08.456684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '374f1afc69e5'
down_revision = '44e15c64a3c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WebPackages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('web_basic_id', sa.Integer(), nullable=False),
    sa.Column('web_standard_id', sa.Integer(), nullable=True),
    sa.Column('web_premium_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['web_basic_id'], ['Webs.id'], ),
    sa.ForeignKeyConstraint(['web_premium_id'], ['Webs.id'], ),
    sa.ForeignKeyConstraint(['web_standard_id'], ['Webs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('listing_img', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=True),
    sa.Column('web_metadata_id', sa.Integer(), nullable=True),
    sa.Column('web_package_id', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['Categories.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['ServiceTypes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['web_metadata_id'], ['WebMegadatas.id'], ),
    sa.ForeignKeyConstraint(['web_package_id'], ['WebPackages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Services')
    op.drop_table('WebPackages')
    # ### end Alembic commands ###
