"""empty message

Revision ID: e29cfc266b8c
Revises: 
Create Date: 2021-06-02 23:57:18.897984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29cfc266b8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Occupations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ProgrammingLanguages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('profile_img', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('date_created', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Webs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('delivery_time', sa.Integer(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('design', sa.Boolean(), nullable=False),
    sa.Column('content_upload', sa.Boolean(), nullable=False),
    sa.Column('source_code', sa.Boolean(), nullable=False),
    sa.Column('revisions', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ReqAnswers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['Requirements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ServiceTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['Categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserLanguages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['Languages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'language_id')
    )
    op.create_table('UserOccupations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('occupation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['occupation_id'], ['Occupations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserSkills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['Skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('WebMegadatas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('programming_language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['programming_language_id'], ['ProgrammingLanguages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('WebPackages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('web_basic_id', sa.Integer(), nullable=False),
    sa.Column('web_standard_id', sa.Integer(), nullable=True),
    sa.Column('web_premium_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['web_basic_id'], ['Webs.id'], ),
    sa.ForeignKeyConstraint(['web_premium_id'], ['Webs.id'], ),
    sa.ForeignKeyConstraint(['web_standard_id'], ['Webs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('listing_img', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=True),
    sa.Column('web_metadata_id', sa.Integer(), nullable=True),
    sa.Column('web_package_id', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['Categories.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['ServiceTypes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['web_metadata_id'], ['WebMegadatas.id'], ),
    sa.ForeignKeyConstraint(['web_package_id'], ['WebPackages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ServiceRequirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['Requirements.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['Services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ServiceRequirements')
    op.drop_table('Services')
    op.drop_table('WebPackages')
    op.drop_table('WebMegadatas')
    op.drop_table('UserSkills')
    op.drop_table('UserOccupations')
    op.drop_table('UserLanguages')
    op.drop_table('ServiceTypes')
    op.drop_table('ReqAnswers')
    op.drop_table('Webs')
    op.drop_table('Users')
    op.drop_table('Skills')
    op.drop_table('Requirements')
    op.drop_table('ProgrammingLanguages')
    op.drop_table('Occupations')
    op.drop_table('Languages')
    op.drop_table('Categories')
    # ### end Alembic commands ###
