"""empty message

Revision ID: cea3dc676a1e
Revises: 8c6f260b1a2b
Create Date: 2021-06-02 19:49:59.178072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea3dc676a1e'
down_revision = '8c6f260b1a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ProgrammingLanguages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ServiceTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['Categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('WebMegadatas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('programming_language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['programming_language_id'], ['ProgrammingLanguages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WebMegadatas')
    op.drop_table('ServiceTypes')
    op.drop_table('ProgrammingLanguages')
    op.drop_table('Categories')
    # ### end Alembic commands ###
